### ISSUE TITLE
Provide a mechanism for setting "ceph.conf" configuration values so they will be in effect during "cephadm bootstrap" phase

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#100]
Nowadays, Ceph has a MON store for cluster configuration, but certain options still have to be set in `ceph.conf` before the cluster is bootstrapped.

One example is `osd crush chooseleaf type = 0`. If this is not provided on the `cephadm bootstrap` command line via the `-c` option, the initial CRUSH map created by `cephadm bootstrap` will have the failure domain set to "host" and there is no easy way to change that.

It's possible that there are other options like this one, which must be set via `cephadm bootstrap -c` in order to properly take effect.

Therefore, I am proposing that ceph-salt provide a mechanism for setting these options.

---

UPDATE: I found another situation where this is needed (and I think it's quite likely that there are more):

If someone needs to run `cephadm bootstrap` with MGR debugging turned up, the only way to do this is via `cephadm bootstrap -c`.

**Comment by sebastian-philipp** [comment]
Hm, that should not end up in the ceph.conf. Instead, I'd put this into the mon store. In general there is only a very limited amout of config that should live within the ceph.conf.

**Comment by smithfarm** [comment]
@sebastian-philipp @trociny Allow me to elaborate a little.

With octopus, we are expected to run "cephadm bootstrap" to start deploying a new cluster. After "ceph-bootstrap" runs, there is a MON, a MGR, a pool, and a CRUSH map (with failure domain "host"), although there are still no OSDs at this point.

On a single-node cluster, however, we typically want the failure domain to be "osd", not "host". Once the CRUSH map is created, however, there is no easy way to modify it. Hence this issue.

Here is the solution I came up with:

```
echo -en "[global]\n        osd crush chooseleaf type = 0\n" > /root/ceph.conf
cephadm bootstrap -c /root/ceph.conf
```

After this command runs, I do not see the option "osd crush chooseleaf type" in ceph.conf. But the value is correctly set to 0 in the MON store, and "ceph osd crush rule dump" shows that the failure domain is set to "osd".

Is this what you meant by "put this into the mon store"?

**Comment by smithfarm** [comment]
I will edit the issue description to emphasize that this mechanism would/should only be used for ceph.conf settings that must be made prior to bootstrapping, like `osd crush chooseleaf type = 0`

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/44284

you're right. the workaround looks ok to me.

**Comment by ricardoasmarques** [comment]
> If someone needs to run cephadm bootstrap with MGR debugging turned up, the only way to do this is via cephadm bootstrap -c.

@smithfarm  Can you please share what exactly has to be added to the `ceph.conf`?

**Comment by ricardoasmarques** [comment]
> > If someone needs to run cephadm bootstrap with MGR debugging turned up, the only way to do this is via cephadm bootstrap -c.
> 
> @smithfarm Can you please share what exactly has to be added to the `ceph.conf`?

Nevermind, `ceph-salt` should be flexible enough to allow the user to set any option.
