### ISSUE TITLE
ceph-salt barfs out a Python traceback (NotImplementedError) when it attempts to add remaining MONs

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#107]
After running "cephadm bootstrap", ceph-salt attempts to create remaining MONs by issuing the command `ceph orch apply mon` but this command was removed by https://github.com/ceph/ceph/commit/a29a78e4e9c732f485e40900c5f00de1804f2d46

As a result, ceph-salt can no longer create remaining MONs. It barfs out a Python traceback similar to this one:

```
Traceback (most recent call last):
File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1002, in apply_mon
raise NotImplementedError()
NotImplementedError
```

There is an upstream orchestrator issue open for this: https://tracker.ceph.com/issues/44302

---

The latest upstream documentation says to use a different command, `ceph orch daemon add mon`, to create additional monitors. This one only takes one MON at a time. See:

https://github.com/ceph/ceph/blob/d27f512d1731988cf7f369559f2fc324f1592047/doc/cephadm/index.rst#deploying-additional-monitors

**Comment by sebastian-philipp** [comment]
will be fixed by https://github.com/ceph/ceph/pull/33548

**Comment by ricardoasmarques** [comment]
Looks like https://github.com/ceph/ceph/pull/33553 re-added the apply command.
