### ISSUE TITLE
Adapt ceph-salt to latest {mon,mgr,osd} deployment UI changes

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#118]
https://github.com/ceph/ceph/pull/33792 was recently merged, which once again changed the command-line UI for creating MONs, MGRs, and OSDs.

ceph-salt will need to be adapted again.

**Comment by bk201** [comment]
For OSD, we need to adapt to this change: https://github.com/ceph/ceph/pull/33922
Either using `orch apply osd`/`orch daemon add osd`, or `orch apply -i` with a big config.

**Comment by sebastian-philipp** [comment]
I think, `orch apply -i` is broken right now. See https://github.com/ceph/ceph/pull/34001
