### ISSUE TITLE
`cephadm bootstrap` add `--skip-monitoring-stack`

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#128]
https://github.com/ceph/ceph/pull/33936

**Comment by smithfarm** [comment]
@sebastian-philipp Can you provide more details only a ceph-salt user would want/need to skip deployment of the monitoring stack?

**Comment by sebastian-philipp** [comment]
the default will install the whole monitoring stack on the bootstrap minion. which is not really want we want to do.

**Comment by sebastian-philipp** [comment]
actually enabling this by default on the bootstrap node is questionable
