### ISSUE TITLE
Cluster comes up in "HEALTH_WARN: clock skew detected"

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#141]
I've been deploying octopus 15.2.0 clusters on SLE-15-SP2 and consistently they are coming up with:

```
HEALTH_WARN
clock skew detected on mon.node
```

The reason for this is ceph-salt starts chronyd on the cluster nodes, but does not wait for them to sync. Typically there is a multi-second (even tens of seconds) skew between the `time_server` cluster node and the external time servers when chronyd first starts. Now, of course, chronyd will eventually sync, but the larger the skew, the longer it takes.

Since this initial health warning has a negative psychological impact on the user (who may not even know what a "clock skew" is), it would be nicer if we avoided the warning by syncing the clocks **before** deploying any MONs.

**Comment by smithfarm** [comment]
closing in favor of https://github.com/SUSE/sesdev/issues/185 for now

**Comment by sebastian-philipp** [comment]
I think we should fix this properly in c-s as well. We shouldn't start clusters deployed with ceph-salt with a clock skew warning

**Comment by smithfarm** [comment]
OK, I will work on this.
