### ISSUE TITLE
Support adding new hosts after initial deployment

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#147]
I have a cluster that was already deployed, but when I try to deploy a new "admin" node, ceph.conf/keyring is not installed and the host is not added to orchestrator:

**How to reproduce**

1) Add new minion, set "admin" role and deploy it
```
# ceph-salt config /ceph_cluster/minions add <new-host-name>
# ceph-salt config /ceph_cluster/roles/admin add <new-host-name>
# ceph-salt deploy <new-host-name>
```

2) Check that, after deployment,  ceph.conf and keyring does not exists on `<new-host-name>:/etc/ceph/`

3) Also, check that the host was not added to orchestrator (regardless of having "admin" role or not)
```
# ceph orch host ls
...
```

**Comment by smithfarm** [comment]
I successfully reproduced this issue. Next, I'll test the fix in #175
