### ISSUE TITLE
Allow users to provide their dashboard cert for bootstrap

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#158]
As far as I can tell from quickly glancing at `ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls`, ceph-salt does not currently let users provide their own dashboard SSL certificate and key via the `--dashboard-crt` and `--dashboard-key` options to `cephadm bootstrap`.

https://github.com/ceph/ceph/pull/33472

**Comment by ricardoasmarques** [comment]
This can be implemented using the new `import` option node, introduced in https://github.com/ceph/ceph-salt/pull/243.
