### ISSUE TITLE
Don't rely on fqdn_ipv4 grain for mon address

### ISSUE THREAD

**Issue by jan--f** [ceph/ceph-salt#160]
We currently rely on the `fqdn_ipv4` grain to populate a nodes public address (see https://github.com/ceph/ceph-salt/blob/master/ceph_salt/core.py#L41). This is not very reliable in that it can contain `127.0.0.1` but also might return an ip address that is from, say a mgmt network.

We need a different way here. Also how can a user influence this choice?

**Comment by smithfarm** [comment]
> how can a user influence this choice?

https://github.com/ceph/ceph-salt/pull/156 seems to fit the bill here?

**Comment by jan--f** [comment]
I think that is one part of the puzzle. We also want to make sure that ceph_salt doesn't set an ip by default, that its own validation will choke on.
Imho the btter option is to take the first non-locahost ipv4 address as default. We can't reliably associate a fqdn with an ip address using only local information anyway.

**Comment by ricardoasmarques** [comment]
> I think that is one part of the puzzle. We also want to make sure that ceph_salt doesn't set an ip by default, that its own validation will choke on.
> Imho the btter option is to take the first non-locahost ipv4 address as default. We can't reliably associate a fqdn with an ip address using only local information anyway.

Yes, given that if we pick a localhost IP, then we will hit https://github.com/ceph/ceph-salt/blob/master/ceph_salt/validate/config.py#L20 validation, so we should try to take first non-localhost address.

@jan--f Maybe we can start by looking into `fqdn_ip4` grains and then fallback to `ip4` grain if no non-localhost ip was find on `fqdn_ip4`? Any other idea?

**Comment by ricardoasmarques** [comment]
Also, we have to fix the chrony config https://github.com/ceph/ceph-salt/blob/master/ceph-salt-formula/salt/ceph-salt/files/chrony.conf.j2#L9 and we should keep in mind that we will have to support IPV6 in the near future.

Maybe we will need a new config so the user can explicitly set the `subnet` to use in chrony.

**Comment by jan--f** [comment]
> > I think that is one part of the puzzle. We also want to make sure that ceph_salt doesn't set an ip by default, that its own validation will choke on.
> > Imho the btter option is to take the first non-locahost ipv4 address as default. We can't reliably associate a fqdn with an ip address using only local information anyway.
> 
> Yes, given that if we pick a localhost IP, then we will hit https://github.com/ceph/ceph-salt/blob/master/ceph_salt/validate/config.py#L20 validation, so we should try to take first non-localhost address.
> 
> @jan--f Maybe we can start by looking into `fqdn_ip4` grains and then fallback to `ip4` grain if no non-localhost ip was find on `fqdn_ip4`? Any other idea?

Yep sounds good to me.

> Maybe we will need a new config so the user can explicitly set the `subnet` to use in chrony.

This is also a good idea. We had the same in deepsea. Its impossible to always guess correctly anyway and real world deployments will have a lot of network devices attached to many networks.

I'm happy to push a PR for the first part (being smarter about guessing the public ip).

**Comment by ricardoasmarques** [comment]
> I'm happy to push a PR for the first part (being smarter about guessing the public ip).

Great, I'll take care of the chrony part https://github.com/ceph/ceph-salt/issues/161
