### ISSUE TITLE
Should be possible to re-apply config on all minions

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#173]
ATM, after initial deployment, configuration can only be applied to one minion at a time:

 ```
ceph-salt deploy <minion_id>
 ```

Depending on the configuration we change, this may result in an inconsistent deployment (e.g SSH keys changed, or time server changed).

Should be possible to re-apply the whole config after initial deployment, by running:
 ```
ceph-salt deploy
 ```

Note that `Reboot` must be skipped for nodes that are already part of the Ceph cluster[1][2]. The following message should be shown in this case:
```
"Minion is already managed by cephadm, please reboot manually"
```

[1] maybe we can use `podman ps` to check if any ceph container is running?
[2] also, we should check if any ceph service is running (in case we are dealing with an upgrade from nautilus to octopus)?

---

Relates to https://tracker.ceph.com/issues/44825
Relates to https://github.com/ceph/ceph-salt/issues/176

**Comment by sebastian-philipp** [comment]
FYI, there is a demand from Ansible to make `bootstrap` idempotent: https://tracker.ceph.com/issues/44825
