### ISSUE TITLE
Root privileges required

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#18]
If the user does not has root privileges, then `ceph-bootstrap` should return immediately.

See: https://github.com/SUSE/DeepSea/blob/master/cli/common.py#L48-L56

**Comment by rjfd** [comment]
We can use the code of deepsea-cli to do this. There is a decorator:
https://github.com/SUSE/DeepSea/blob/master/cli/common.py#L48-L56
that can be used to control which commands of ceph-bootstrap require root privileges: https://github.com/SUSE/DeepSea/blob/master/cli/deepsea.py#L272
