### ISSUE TITLE
"ceph-salt deploy --non-interactive" returns exit status zero on failure

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#180]
Recently we saw a transient failure when running the following command:

```
stdbuf -o0 ceph-salt -ldebug deploy --non-interactive
```

The exit status was `0` which, if confirmed, would be a bug (and hence this issue).

Since `stdbuf -o0 false` returns exit status 1, I don't think `stdbuf` is the cause. It seems like `ceph-salt deploy` itself is returning 0 even in the failure case.

**Comment by sebastian-philipp** [comment]
please reopen, if still reproducible.
