### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#19]
It should be possible to set if we want to use IPv4 or IPv6.

A new config entry should be created:

```
/Network/Address_Family
```
whith the following commands available:

- `set ip4`
- `set ip6`

**Comment by ricardoasmarques** [comment]
Note that by default, `ceph-salt` will assign IPv4 bootstrap Mon IP and chrony subnet, but it's now possible to explicitly changed those values manually.

The only thing we need to do before closing this issue is verifying that if we explicitly set IPv6 address and subnet, everything will work as expected.

**Comment by ricardoasmarques** [comment]
Blocked by https://tracker.ceph.com/issues/45016

**Comment by LenzGr** [comment]
FYI, https://tracker.ceph.com/issues/45016 has been resolved in the meanwhile. Removing the "blocked-by-cephadm" label.

**Comment by ricardoasmarques** [comment]
I was able to deploy an IPv6 cluster by using the following `sesdev` PR, so this issue can now be closed: https://github.com/SUSE/sesdev/pull/56
