### ISSUE TITLE
Unable to see dashboard password

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#192]
For security reasons we are hiding the dashboard password on `ls` command, but we should have an `info` command on dashboard password node that can be used to see the password.

**Comment by jschmid1** [comment]
> but we should have an `info` command on dashboard password node that can be used to see the password.

+1

**Comment by ricardoasmarques** [comment]
Note that if the password was not explicitly set, then user will have to look into `/var/log/ceph/cephadm.log` on bootstrap minion to see which password was generated.

We can simplify this, by generating the random password in `ceph-salt`.

**Comment by smithfarm** [comment]
It's also possible to set a flag instructing the dashboard to force the user to change the password on first login. So, the default behavior could be: "if the user does not set the dashboard username/password explicitly, set it to admin/admin and turn on said flag".
