### ISSUE TITLE
`ceph-salt config` first run complains it can't read prefs.bin

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#194]
The first time I run `ceph-salt config`, I see a warning:

```
# ceph-salt config
Warning: Could not load preferences file /root/.ceph_salt_config_shell/prefs.bin.
```

Presumably that's just because the file doesn't exist yet. I'd suggest changing this to only warn if the file actually exists, but can't be read.

**Comment by ricardoasmarques** [comment]
Perhaps something to fix on `configshell` directly: https://github.com/open-iscsi/configshell-fb/blob/master/configshell/shell.py#L173

**Comment by tserong** [comment]
Good idea, I've opened https://github.com/open-iscsi/configshell-fb/pull/56

**Comment by tserong** [comment]
So that's merged in configshell. Next we'd have to wait for an upstream release from there, and a subsequent downstream update in SLE before that warning goes away. There shouldn't be any actual changes required inside ceph-salt though :-)

**Comment by ricardoasmarques** [comment]
Fixed in `cofigshell-fb`.
