### ISSUE TITLE
After initial reboot `ceph-salt deploy` says it can't find ceph-salt formula

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#196]
Seen on SLE 12 SP2 with salt-3000 and ceph-salt-15.2.1+1587155350.g440cd72.

Initial run of `ceph-salt deploy` resulted in reboot of all nodes, with master node saying "Salt master must be rebooted manually", as shown here:

![salt-master-must-be-rebooted-manually](https://user-images.githubusercontent.com/754700/79982914-5adf0380-84ea-11ea-8003-d4e795bb4316.png)

After rebooting the master, subsequent runs of `ceph-salt deploy` resulted in:

```
# ceph-salt deploy
Checking if ceph-salt formula is available...
salt-master will be restarted to load ceph-salt formula
Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed
```

Of course, ceph-salt forumula *is* installed. The problem is somehow related to two minions not picking up the ceph-salt:execution:provisioned and/or ceph-salt:execution:failed grain correctly (two minions were printing `[salt.loaded.int.module.cmdmod:397 ][INFO    ][1310] Executing command 'ssh -o StrictHostKeyChecking=no -i /tmp/ceph-salt-ssh-id_rsa root@node1 'salt-call grains.get --out=json --out-indent=-1 ceph-salt:execution:provisioned'' in directory '/root'` every five seconds in /var/log/salt/minion).

Eventually a timeout was hit (https://github.com/ceph/ceph-salt/blob/master/ceph-salt-formula/salt/_states/ceph_salt.py#L62) and `ceph-salt deploy` started behaving correctly again.

**Comment by ricardoasmarques** [comment]
@tserong did you manually killed `ceph-salt` process and rebooted master node before non-master nodes finished the deployment? I mean, before the `q (quit)` command became available in the UI?

**Comment by tserong** [comment]
Um... Probably? IIRC the other nodes had rebooted, but the `q` command was not available? But I'm not 100% certain. Should I re-test to confirm?

**Comment by tserong** [comment]
Yep, I reckon I did manually kill ceph-salt and reboot the master last time.

I've done another run from scratch (keeping my hands off), and now have:

- master says it must be rebooted manually
- node1 says "one or more minions failed" waiting for other minions
- node2 and node3 are stuck in "wait for an admin host" for the last 25 minutes. I assume they will remain like that forever now :-)
- there's no way to quit (see #195)

![ceph-salt deploy master and node1](https://user-images.githubusercontent.com/754700/80186303-25085f00-8651-11ea-8a52-dc951f757f8d.png)
![ceph-salt deploy node2 and node3](https://user-images.githubusercontent.com/754700/80186306-26398c00-8651-11ea-9c12-d65ed478c4a9.png)

**Comment by tserong** [comment]
Oops, spoke too soon. node2 and node3 did eventually hit a timeout after 30 minutes(!) and I was able to quit. Then I rebooted the master and ran `ceph-salt deploy` again, which now seems to be doing the right thing...

**Comment by tserong** [comment]
...yep, worked the second time through.
![ceph-salt deploy worked second time](https://user-images.githubusercontent.com/754700/80187734-7dd8f700-8653-11ea-82df-c45c5955a774.png)

**Comment by ricardoasmarques** [comment]
This bug was introduced in https://github.com/ceph/ceph-salt/pull/175

**Comment by nistiwar** [comment]
In my case, there was no reboot required during ceph-salt update.However, when applying the configuration, it is stuck at "Find an admin host" for all the cluster nodes, including the admin node itself. Its been more than 35 minutes in the same state. Should the admin node minion not go under cephadm ?

**Comment by tserong** [comment]
@nistiwar from your description, ISTM you're experiencing a different error than "can't find ceph-salt formula". If you still have the problem, can you please open a separate issue and provide more details so we can track this better?

**Comment by nistiwar** [comment]
I think this is sorted now. It was due to firewall issues that I was facing
all the trouble.

Thanks for asking though.
