### ISSUE TITLE
Support multiple Ceph clusters on the same Salt cluster

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#197]
ATM, only one Ceph cluster per Salt cluster is supported. How can we adapt `ceph-salt` to support multiple Ceph clusters on the same Salt cluster?

**Comment by smithfarm** [comment]
I have an idea: provide a command that would repeat the exact same `cephadm bootstrap` command that was already performed once, just with a different `--fsid`?
