### ISSUE TITLE
Bootstrapping with "salt ... state.apply" (instead of "ceph-salt deploy") appears to be broken

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#198]
The output is quite long, so I put it here: https://paste2.org/zWszbI85

**Comment by ricardoasmarques** [comment]
@smithfarm When you want to run the formula directly from salt, you need to perform some additional setup steps (that `ceph-salt apply` do automatically for you) - see https://github.com/ceph/ceph-salt/blob/master/README.md

```
master:~ # salt -G ceph-salt:member state.apply ceph-salt
<FAILS DUE TO MISSING/UNKOWN MODULES>
```

but

```
master:~ # systemctl restart salt-master
master:~ # salt \* saltutil.sync_all
master:~ # salt -G ceph-salt:member state.apply ceph-salt
<SUCCEED>
```
Can you confirm that if you restart `salt-master` and do `salt sync all` before applying the formula, it succeeds?
