### ISSUE TITLE
Issuing a series of "ceph-salt config" commands is tedious

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#204]
Currently, bootstrapping a Ceph cluster using `ceph-salt` involves issuing a series of

    ceph-salt config

commands. Each of these commands takes a long time (approximately 5 seconds) to complete. 

Apparently, this is because each invocation of `ceph-salt config` builds the entire configshell tree (i.e. from `/`) even when not needed. 

Please consider making some optimization.

**Comment by toabctl** [comment]
Fully agree. You could use something like
```
ceph-salt config <<EOF
ls
# another command
EOF
```

to not have the startup time for each command..

**Comment by ricardoasmarques** [comment]
PR https://github.com/ceph/ceph-salt/pull/224 improves `ceph-salt config` performance significantly.
