### ISSUE TITLE
Disabling time server functionality causes "ceph-salt apply" to fail 100% of the time

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#208]
It's possible to disable `time server` configuration in `ceph-salt`, but if we do it then we will hit the following error when applying the config:

![Screenshot from 2020-04-29 16-03-59](https://user-images.githubusercontent.com/14297426/80615792-0bdc2580-8a38-11ea-8127-b771380532bc.png)

**Comment by smithfarm** [comment]
Actually, I think this is just working as expected. If the user does not specify a time_server host via `ceph-salt config`, it is assumed that the user has already configured time synchronization on all the minions via some other mechanism.

**Comment by smithfarm** [comment]
Maybe `ceph-salt` could issue a warning in this case, or perhaps we should force the user to take some affirmative action, like 

    ceph-salt config /time_sync false

The "time_sync" value could default to true, and if it is true and no time_server host has been set, then we raise an error in validate_config?

**Comment by ricardoasmarques** [comment]
@smithfarm You are right, if user explicitly disables it by running `ceph-salt config /time_server disable`, we can assume that time_server will be configured by the user. If not, then we will correctly hit the `cephadm check-host` failure. 

Closing the issue...

**Comment by smithfarm** [comment]
When `/time_server` is disabled, we'll check all hosts with `cephadm` role, as part of the validation stage before the Salt Formula is triggered, to ensure that they have a time sync service active. This will essentially be a duplication of the check that `cephadm check-host` will do later. The purpose of duplicating it is to fail earlier and make it clear to the user that, having disabled `/time_server` in ceph-salt, they must configure and start time sync services on all their hosts before trying to deploya Ceph cluster.

**Comment by smithfarm** [comment]
```
def check_time_sync(enabler=None):
    # type: (Optional[Packager]) -> bool
    units = [ 
        'chrony.service',  # 18.04 (at least)
        'chronyd.service', # el / opensuse
        'systemd-timesyncd.service',
        'ntpd.service', # el7 (at least)
        'ntp.service',  # 18.04 (at least)
    ]   
    if not check_units(units, enabler=None):
        logger.warning('No time sync service is running; checked for %s' % units)
        return False
    return True
```

And `check_units` is just a simple wrapper around:

```
def check_unit(unit_name):
    # type: (str) -> Tuple[bool, str, bool]
    # NOTE: we ignore the exit code here because systemctl outputs
    # various exit codes based on the state of the service, but the
    # string result is more explicit (and sufficient).
    enabled = False
    installed = False
    try:
        out, err, code = call(['systemctl', 'is-enabled', unit_name],
                              verbose_on_failure=False)
        if code == 0:
            enabled = True
            installed = True
        elif "disabled" in out:
            installed = True
    except Exception as e:
        logger.warning('unable to run systemctl: %s' % e)
        enabled = False
        installed = False

    state = 'unknown'
    try:
        out, err, code = call(['systemctl', 'is-active', unit_name],
                              verbose_on_failure=False)
        out = out.strip()
        if out in ['active']:
            state = 'running'
        elif out in ['inactive']:
            state = 'stopped'
        elif out in ['failed', 'auto-restart']:
            state = 'error'
        else:
            state = 'unknown'
    except Exception as e:
        logger.warning('unable to run systemctl: %s' % e)
        state = 'unknown'
    return (enabled, state, installed)
```

**Comment by smithfarm** [comment]
I'm reluctant to duplicate a bunch of cephadm code in ceph-salt unless it's really needed. Putting this on hold for now.
