### ISSUE TITLE
MGRs are using the localhost network as in  `127.0.0.1:6800`

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#21]
```
$ ceph mgr dump
...
    "active_addrs": {
        "addrvec": [
            {
                "type": "v2",
                "addr": "127.0.0.1:6800",
                "nonce": 1
            },
            {
                "type": "v1",
                "addr": "127.0.0.1:6801",
                "nonce": 1
            }
        ]
    },
```
We should make sure, MGRs use proper addresses.

**Comment by rjfd** [comment]
The problem is caused when a machine has its FQDN pointing to the loopback interface address:
```
dummy-node:~ # cat /etc/hosts
127.0.0.1 dummy-node.test.com dummy-node
```

ceph-bootstrap currently chooses the IP address for the MONs based on the `fqdn_ip4` salt grain, which with the above `/etc/hosts` configuration will return the loopback interface IP address.
