### ISSUE TITLE
"ceph-salt config" is slow on large clusters

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#222]
With 104 nodes in the config, `ceph-salt` takes almost 3 minutes to open the shell:

```
master:~ # time ceph-salt config
/> exit

real	2m38.294s
user	0m28.353s
sys	0m1.543s
```

**Comment by ricardoasmarques** [comment]
Let's start by doing a *lazy* load of grains [1] (only do the first read when asked for, and then cache values), and then check how it improves the performance.

[1] https://github.com/ceph/ceph-salt/blob/master/ceph_salt/core.py#L28

**Comment by ml8mr** [comment]
Would it be helpful to report a message like "Analyzing environment..." immediately after running ceph-salt? This won't fix anything, but may prevent someone from hitting ctrl-c and searching for something that might be preventing the tool from even running.

**Comment by ml8mr** [comment]
> Would it be helpful to report a message like "Analyzing environment..." immediately after running ceph-salt? This won't fix anything, but may prevent someone from hitting ctrl-c and searching for something that might be preventing the tool from even running.

Given the great improvement in load times with Ricardo's latest PR, adding this message may not be necessary after all.  :)
