### ISSUE TITLE
Add ability to pause interactive screen refreshes

### ISSUE THREAD

**Issue by ml8mr** [ceph/ceph-salt#226]
When running `ceph apply` interactively, it may be helpful to pause screen refreshes. This would aid in analyzing error messages, particularly in large environments. Ideally, this would also allow copy and paste from the interactive shell output.

If this is possible, it should be added as "(p)ause" (similar to the already existing "(c)ollapse" option). (Although there is a risk that people will assume that implies suspending all operations.)

**Comment by ricardoasmarques** [comment]
Some ideas to try to avoid the `(p) pause <-> suspend all operation` ambiguity.

1) I'm not sure if it's possible to implement, but it would be great if we can automatically pause the refresh when we detect that the user has any text selected.

2) If we can't do 1), then we can consider pausing the refresh if the user keeps `shift` key pressed.

3) After execution is complete we no longer display the loading icon, so we can switch from "periodic refresh" to "reactive refresh" (only refresh UI when needed).

4) Or find another name for the initial "(p) pause" proposal
