### ISSUE TITLE
`ceph-salt export` logs private ssh key and dashboard password to /var/log/ceph-salt.log

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#229]
When running `ceph-salt config ls`, the private ssh key is (correctly) not included in the log by the PillarManager.get() function, which looks like it's being called for every value individually (the dashboard password will also be skipped once #228 goes in). However, when running `ceph-salt export`, it calls PillarManager.get('ceph-salt'), which dumps the entire pillar contents, so everything in the pillar, including the private ssh key and dashboard password land in /var/log/ceph-salt.log

**Comment by smithfarm** [comment]
Something to keep in mind: the purpose of "ceph-salt export" is to produce output that can later be passed to "ceph-salt import", to reproduce the configuration (e.g., when starting again from a clean slate). To the extent that the dashboard username and password are part of the configuration, they need to be included in the export output.

Not that I am against being safe and not writing secrets to stdout or a file. Perhaps we need to think about how to have our cake and eat it, too.

Clearly, there needs to be a way (maybe not the default) to preserve the current behavior. Some sites may not have a need to strictly guard the secrecy of this password. On the other hand, when we do not write out the password, it has to be done in a way that doesn't break "ceph-salt import".

**Comment by tserong** [comment]
It's totally fine for `ceph-salt export` to dump everything to the export output (if it didn't, `ceph-salt import` wouldn't work, as you say). The thing I object to is that everything is *also* simultaneously dumped to /var/log/ceph-salt.log.

**Comment by smithfarm** [comment]
Oh. I didn't realize export was logging. Thanks for the clarification!
