### ISSUE TITLE
ceph-salt should enforce a password change for the dashboard admin user upon first login

### ISSUE THREAD

**Issue by LenzGr** [ceph/ceph-salt#232]
For security reasons, the admin user account that gets created by ceph-salt should be configured to enforce a change of their password upon the first login.

This can be accomplished by adding the option `--pwd_update_required` to the`ceph dashboard ac-user-create` call that creates the admin user account.

**Comment by sebastian-philipp** [comment]
See

https://github.com/ceph/ceph/blob/47d737c51795a6f4b8057275462c328a3f13d332/src/cephadm/cephadm#L2628-L2629

**Comment by ricardoasmarques** [comment]
Already implemented on the following open PR https://github.com/ceph/ceph-salt/pull/220
