### ISSUE TITLE
Need to invoke `ceph orch apply crash`

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#236]
We need to add a call to `ceph orch apply crash` to make the orchestrator deploy the ceph-crash service. Without this, ceph crashes never get posted, so won't appear in `ceph crash stat` or `ceph crash ls` (`cephadm bootstrap` would normally do this, but we're calling it with `--skip-ssh`, so don't get this behaviour by default - see also https://tracker.ceph.com/issues/45572).

**Comment by sebastian-philipp** [comment]
I personally don't like to simply run `ceph orch apply crash` without any placement specs. 

I know how it works, but it I doubt that everyone knows the default placement specs for each service.

I'd like to make `--placement` mandatory and force users to run `ceph orch apply crash --placement '*'`

**Comment by tserong** [comment]
I agree that nobody will know WTF the default placement specs are, and users should explicitly specify a placement when they deploy a service. For the crash service though, I still think we should automate this, i.e. ceph-salt should run `ceph orch apply crash '*'`, without the user having to do it by hand.

**Comment by sebastian-philipp** [comment]
which is already the caes, as crash is automatically enabled if you don't say --skip-ssh

Maybe we should change the behavior of --skip-ssh to align it with expectations?

I.e. why skipping `apply crash '*'` if we don't have any hosts, that's unrelated

**Comment by tserong** [comment]
Yeah, but ceph-salt *does* say --skip-ssh :-)

--skip-ssh also skips `ceph mgr module enable cephadm`, and `ceph orch set backend cephadm`. So maybe --skip-ssh should be changed to *only* skip ssh, and still have `cephadm boostrap` enable the cephadm module? In which case, ceph-salt wouldn't need to do those latter things anymore.

**Comment by sebastian-philipp** [comment]
yes yes yes yes

**Comment by ricardoasmarques** [comment]
@tserong @sebastian-philipp FYI, I've submitted a `cephadm` issue - https://tracker.ceph.com/issues/45629
