### ISSUE TITLE
Local registry setup

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#237]
It would be useful if `ceph-salt` provides a **role** to setup a local registry[1].

We can also including front web server (nginx), certificate generation, and certificate acceptance in all nodes.

[1] https://github.com/SUSE/doc-ses/commit/647470da12de867c13d7fb82905106dc32b3b09c#diff-a5976e7fca1dfd90ad89dd2666a99ba7R579

**Comment by bk201** [comment]
Airgapped deployment in CaaSP (not only registries, but also package mirroring and more)
https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#_airgapped_deployment

**Comment by ricardoasmarques** [comment]
Moved to https://github.com/SUSE/sesdev/issues/388

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/47286
