### ISSUE TITLE
Cephadm bootstrap: Failed to connect to node..

### ISSUE THREAD

**Issue by Christian-Rau** [ceph/ceph-salt#256]
After running these steps:
```
curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
chmod +x cephadm
mkdir -p /etc/ceph
./cephadm bootstrap --mon-ip **public-IP-here**
```
Its running fine until:

INFO:cephadm:Wrote public SSH key to to /etc/ceph/ceph.pub
INFO:cephadm:Adding key to root@localhost's authorized_keys...
INFO:cephadm:Adding host node-XXX...

INFO:cephadm:Non-zero exit code 2 from /usr/bin/docker run --rm --net=host -e CONTAINER_IMAGE=docker.io/ceph/ceph:v15 -e NODE_NAME=node-XXX-v /var/log/ceph/137d983c-a33d-11ea-ae56-0050563e8b06:/var/log/ceph:z -v /tmp/ceph-tmp4rbhy9rq:/etc/ceph/ceph.client.admin.keyring:z -v /tmp/ceph-tmp9zzvvdav:/etc/ceph/ceph.conf:z --entrypoint /usr/bin/ceph docker.io/ceph/ceph:v15 orch host add node-XXX
__
_I get this error:_
stderr Error ENOENT: Failed to connect to node-XXX (node-XXX).  Check that the host is reachable and accepts connections using the cephadm SSH key

I even played nice and changed my SSH ports, back to default, for the entire swarm-cluster.. As I thought that caused the issue.
The keys are "Adding key to root@localhost's authorized_keys..."

Are there some initial steps to be taken to pave the road so the setup runs as smooth as butter?

**Comment by Christian-Rau** [comment]
After doing some SSH key checking as proposed in the docs. I found that the problem was that I had closed down **root access** when I changed my SSH port to default!

I hope this gets fixed. - I maybe even better, with a decent plugin for cockpit/Debian!
_now I have to find out if I can shut root access again?_

**Comment by ne7atuve** [comment]
Hi Christian, I have the same problem, could you please leave an email to contact me, I really need help !!!
