### ISSUE TITLE
UX: Setting the bootstrap minion should also set the `admin` role and the `cephadm` role

### ISSUE THREAD

**Issue by toabctl** [ceph/ceph-salt#272]
When setting the bootstrap minion, this minion should automatically added to the `roles/admin` and `roles`cephadm` list.
Otherwise you have to do theses steps manually.

```
/ceph_cluster/roles/bootstrap> ls
o- bootstrap ........................................................................................................... [no minion]               
/ceph_cluster/roles/bootstrap> set node1.ses7-manual.com
Value set.
/ceph_cluster/roles/bootstrap> exit
master:~ # ceph-salt apply
Bootstrap minion must be 'Admin'
```

When then adding the same node to the admin role and trying to apply again, I get:
```
master:~ # ceph-salt apply
Minion 'node1.ses7-manual.com' has 'admin' role but not 'cephadm' role
```

So next manual step is:

```
/ceph_cluster/roles/cephadm> add node1.ses7-manual.com
Adding node1.ses7-manual.com...
1 minion added.
/ceph_cluster/roles/cephadm> exit

```

**Comment by ricardoasmarques** [comment]
Or we should consider removing this requirement, and don't force the `bootstrap minion` to be `admin`.

**Comment by LenzGr** [comment]
FWIW I'd be in favor to decouple this as well. In my case, I would like to have on central node to SSH into if necessary, which also acts as the Salt Master node. While the bootstrap minion acts as the "initial seed node", it may not necessarily be the node used for regular admin work.

**Comment by LenzGr** [comment]
Is this related to #252 by any chance?
