### ISSUE TITLE
Inconsistent tab-completion behavior in `ceph-salt config`

### ISSUE THREAD

**Issue by LenzGr** [ceph/ceph-salt#284]
Just a minor usability issue: I noticed that tab completion does not work when trying to modify a configuration option from within the configuration group.

For example, I can do a `cd /cephadm_bootstrap/dashboard>` to change into the `dashboard` config group using tab completion quickly. But once inside that group, I can not complete the option name using the Tab key, I need to type out the complete option name, e.g. `set cephadm_bootstrap/dashboard/username ceph-admin`. It would be nice to support tab completion for the config options as well.

**Comment by ricardoasmarques** [comment]
@LenzGr you are using the wrong syntax. If your first argument is the path, `tab` behaves as expected:

```
/> cd /cephadm_bootstrap/dashboard/
/cephadm_bootstrap/dashboard> username/ set ceph-admin
Value set.
```

**Comment by LenzGr** [comment]
This indeed works, thanks! But I must admit that I find this order quite confusing - I can do a `cd <path>` and an `ls <path>`, and I just noticed that `<path> ls` works as well. And for changing something, I would find it more logical to start with the command, followed by the object that I would like to change (like in a regular shell). But I understand that's a limitation of the `config-shell` module we're using here, so this probably has to be addressed there.
