### ISSUE TITLE
`ceph-salt config` does not support modifying config options from outside the configuration group

### ISSUE THREAD

**Issue by LenzGr** [ceph/ceph-salt#285]
It would be nice if it would be possible to modify configuration options from within the "root" of the configuration tree, including full tab support up to and including the actual config option (see #284 for a related issue).

For example, it would be nice if the following would not fail:
```
/> set /cephadm_bootstrap/dashboard/username ceph-admin
Command not found set
```

**Comment by ricardoasmarques** [comment]
You are using incorrect syntax, config path should be the first thing:

```
/> set /cephadm_bootstrap/dashboard/username ceph-admin
Command not found set

/> /cephadm_bootstrap/dashboard/username set ceph-admin
Value set.
```

**Comment by LenzGr** [comment]
This works indeed - thanks. However, this feels somewhat unintuitive, but I understand it needs to be fixed in the `configshell` Python module itself.
