### ISSUE TITLE
Unalias the ceph container image tag before sending it to cephadm

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#300]
As https://jira.suse.com/browse/SES-2017 explains, it will not be allowed to specify a ":latest" tag (or any other tag that isn't absolute, final, immutable) on the ceph container image path. That also means it won't be allowed to specify an image path without an explicit tag (since that would default to ":latest").

Since this will be confusing and bothersome for customers who are not accustomed to entering a long, complicated version number (the container image tag will be something like this: `:15.2.4.89.3.43`, which may not seem complicated to us developers, but is difficult for many people to type in correctly, and having to type it in is certainly bothersome for anyone, developers included).

This feature request is for ceph-salt to be patched so it queries the registry to find out which full version number tag corresponds to the container image path given by the user. (Some tags, such as ":latest" are just pointers to immutable tags. The immutable tag will be visible once the container image is downloaded.) Once the immutable tag is known, ceph-salt can munge the container image path to use the immutable tag. By "immutable tag" we mean a tag that has six version number components x.y.z.a.b.c, e.g. `:15.2.4.89.3.43`.

**Comment by smithfarm** [comment]
This might be relatively simple to implement. We could allow the user to specify any tag, or no tag. Once the container image has been downloaded (`podman pull`), the immutable tag can be determined just by looking which image was downloaded. Then ceph-salt can munge the image path value in the config store (changing the tag given by the user to the immutable tag) and then pass the munged image path to `cephadm bootstrap`.

**Comment by ricardoasmarques** [comment]
Relates to https://github.com/ceph/ceph/pull/36432

**Comment by sebastian-philipp** [comment]
yep. please wait with this. I'd like to fix this in cephadm

**Comment by sebastian-philipp** [comment]
can we close this?

**Comment by smithfarm** [comment]
@sebastian-philipp This is tracking https://jira.suse.com/browse/SES-2017 for purposes of ceph-salt. Has something changed in https://jira.suse.com/browse/SES-2017 ?

**Comment by ricardoasmarques** [comment]
Per our discussion, all we have to do here is call:

```
ceph config set mgr mgr/cephadm/use_repo_digest true --force
```

**Comment by ricardoasmarques** [comment]
We can do it here: https://github.com/ceph/ceph-salt/blob/master/ceph-salt-formula/salt/ceph-salt/apply/ceph-admin.sls#L18

**Comment by smithfarm** [comment]
> Per our discussion, all we have to do here is call:
> 
> ```
> ceph config set mgr mgr/cephadm/use_repo_digest true --force
> ```

We can only do that once  https://github.com/ceph/ceph/pull/36432 has been backported to octopus and included in a SES7 ceph build, right?
