### ISSUE TITLE
Edit "/etc/systemd/journald.conf" on behalf of the user

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#304]
If the `/var/log/journal` directory does not exist (or does not have the right permissions/ownership), systemd will not persist log messages emitted by daemons running in containers. In such a case, the journal will be stored in memory, with the result that the vast majority of log messages will be lost: only the very most recent ones will be stored in memory.

It seems highly likely that the SLE default setting will be `storage=auto`, which means that we can only hope that the directory will be created properly before the user starts running Ceph.

The directory can be created properly by:

1. edit `/etc/systemd/journald.conf`: change `#storage=auto` to `storage=persistent`
2. `systemctl restart systemd-journald`

These commands could be run on each minion by `ceph-salt apply` to ensure that SES7 installations have a persistent journal from the start.

I believe it's worth considering for ceph-salt to automatically correct this setting.

If we're worried that there might be some user who objects to this behavior, there could be a config setting to disable it.

I personally can't imagine why a user would want to keep "storage=auto" on a Ceph Octopus cluster node, though. One reason for keeping the journal in memory is that `rsyslogd` is running. I don't know whether Ceph Octopus daemons (running in containers) can log to rsyslogd (running on the host), though.

**Comment by ricardoasmarques** [comment]
@smithfarm  Since https://github.com/ceph/ceph-salt/pull/244 `ceph-salt` is creating the `/var/log/journal` directory, isn't it sufficient for SLE where `storage=auto`? Or the motivation for this issue is to persist logs also on systems where `storage=auto` is not the default setting?

**Comment by smithfarm** [comment]
@ricardoasmarques On my systems, I set `storage=persistent`. But I guess this should be left to the users. So I think we are doing the right thing by (1) not touching the configuration file, and (2) creating the directory if it doesn't exist.
