### ISSUE TITLE
registries.conf should also have unqualified-search-registries = ["docker.io"]

### ISSUE THREAD

**Issue by Martin-Weiss** [ceph/ceph-salt#309]
registries.conf should also have unqualified-search-registries = ["docker.io"]

(just in case other containers are used later on..)

**Comment by sebastian-philipp** [comment]
ok this now conflicts with https://github.com/ceph/ceph/pull/36315

Either we go with proper search registries or we don't.  cc @p-se

**Comment by Martin-Weiss** [comment]
> 
> 
> ok this now conflicts with [ceph/ceph#36315](https://github.com/ceph/ceph/pull/36315)
> 
> Either we go with proper search registries or we don't. cc @p-se

I so not think this is a conflict.. we just need the default for unqualified searches..

 /etc/containers/registries.conf:

```
unqualified-search-registries = ["docker.io"]
[[registry]]
prefix = "registry.suse.com"
location = "my-private-registry.mydomain.com:5000/prod/registry.suse.com"
```

**Comment by Martin-Weiss** [comment]
If we do not have internet access we go even further like this:
```

unqualified-search-registries = ["docker.io"]
[[registry]]
prefix = "registry.suse.com"
location = "my-private-registry.mydomain.com:5000/prod/registry.suse.com"
[[registry]]
prefix = "docker.io"
location = "my-private-registry.mydomain.com:5000/prod/docker.io"
[[registry]]
prefix = "docker.io/library"
location = "my-private-registry.mydomain.com:5000/prod/docker.io"
```
