### ISSUE TITLE
Need a way to get the configuration database in JSON

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#32]
Please implement a way to dump the configuration database in JSON. For example, a `--format json` switch for `ceph-bootstrap config ls`. Thanks!

**Comment by rjfd** [comment]
@smithfarm what if we implement a `ceph-bootstrap config export` that dumps a JSON of the configuration? 

And in the future we might be able to "import" the same JSON...

**Comment by smithfarm** [comment]
@rjfd Works for me!
