### ISSUE TITLE
In theory, "ceph-salt apply" should be idempotent, but in practice there are issues

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#327]
It seems fairly easy to get a cluster into the following state by re-running "ceph-salt apply" and interrupting it while it's still running:

```
# ceph-salt apply
Checking if ceph-salt formula is available...
salt-master will be restarted to load ceph-salt formula
Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed
```

Now, I understand I'm not supposed to interrupt it, and "ceph-salt apply" tries to make it difficult for me to do so, but we cannot just say: "don't interrupt it while it's running". What if the user experiences a power failure while it's running?

Also, it's not clear why this error message is displayed in this case. The ceph-salt-formula package is installed (of course).

Worse yet, it's not clear how to recover. I've heard of people completely re-imaging their bare metal nodes in order to re-run "ceph-salt apply" when something goes wrong. There should be a better way?

**Comment by ricardoasmarques** [comment]
Yes, that message is displayed when there are `ceph-salt` salt jobs still running, we should try to add a check for that and/or be able to force `quit`.

Related to https://github.com/ceph/ceph-salt/issues/195

**Comment by smithfarm** [comment]
`ceph-salt apply` could check for running jobs:

```
master:~ # salt-run jobs.active
[INFO    ] Runner completed: 20200824110846544316
```

and, if they are detected, educate the user how to kill them?

**Comment by smithfarm** [comment]
`salt '*' saltutil.kill_all_jobs` 
(or
`salt '*' saltutil.kill_job <job id>` if you don't want to kill all jobs)

**Comment by smithfarm** [comment]
we are seeing this error when we interrupt a running ceph-salt apply, and then want to re-start it
This issue can be stated in a slightly different way.

We are seeing this issue after we "interrupt" a running `ceph-salt apply`. There are two ways to do this:

1. when `ceph-salt apply` runs in "non-interactive" mode, one can simply hit CTRL-C a couple times to interrupt it
2. when `ceph-salt apply` runs in interactive mode, it can be interrupted by killing the front-end process

In either case, `ceph-salt apply` is not actually terminated. It continues to run even when "interrupted".

Somehow that causes this code to trigger:

```
        result = SaltClient.local_cmd('ceph-salt:member', 'state.sls_exists', [state],
                                      tgt_type='grain')
        if not all(result.values()):
            logger.error("%s formula still not found", state)
            PP.pl_red("Could not find {} formula. Please check if ceph-salt-formula package "
                      "is installed".format(state))
```

But it's not clear why that is.

**Comment by smithfarm** [comment]
I can reproduce the issue at will by:

1. `ceph-salt apply --non-interactive`
2. wait for it to reach at least `[STAGE] [BEGIN] Sync clocks`
3. hit CTRL-C twice
4. `ceph-salt apply --non-interactive` (fails with "Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed")

I also tried running `salt -G ceph-salt:member state.sls_exists ceph-salt` when the Salt cluster is in this state. Here is the result:

```
master:~ # salt -G ceph-salt:member state.sls_exists ceph-salt
node2.ses7.test:
    False
node1.ses7.test:
    False
master.ses7.test:
    False
node3.ses7.test:
    False
```

After awhile (presumably, when the running Salt jobs complete), the issue goes away and it is again possible to run `ceph-salt apply`.

**Comment by smithfarm** [comment]
As discussed with @ricardoasmarques we can check for this state by doing:

```
salt -G 'ceph-salt:member' saltutil.running
```

This checks if there are any Salt jobs running on the `ceph-salt:member` nodes. In this case, it's likely that a missing "ceph-salt-formula" is not the problem and we should display a different error message.
