### ISSUE TITLE
"ceph-salt apply" has minions use ssh to check grains on other minions - add a sanity check for this?

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#328]
In "ceph-salt-formula/salt/_states/ceph_orch.py" we have this code:

```
                sudo = 'sudo ' if ssh_user != 'root' else ''
                status_ret = __salt__['cmd.run_all']("ssh -o StrictHostKeyChecking=no "
                                                     "-i /tmp/ceph-salt-ssh-id_rsa {}@{} "
                                                     "'if [[ -f /etc/ceph/ceph.conf "
                                                     "&& -f /etc/ceph/ceph.client.admin.keyring ]]; "
                                                     "then timeout 60 {}ceph -s; "
                                                     "else (exit 1); fi'".format(
                                                         ssh_user,
                                                         admin_host,
                                                         sudo))
```

In https://bugzilla.suse.com/show_bug.cgi?id=1175561 we found that when we tried to ssh from one minion to another in this way, SSH just asked for a password.

That gave me the following idea: when the user initiates `ceph-salt apply`, several sanity checks are run. Could we include a sanity check for the ability of a minion to check grains of another minion using SSH?

**Comment by ricardoasmarques** [comment]
SSH is configured by `ceph-salt` so I believe it's safe to assume it's well configured.

Perhaps, what we need to validate before-hand is that all hosts can resolve other hostnames?

**Comment by smithfarm** [comment]
wip branch: https://github.com/smithfarm/ceph-salt/commits/wip-328
