### ISSUE TITLE
ceph-salt status/apply: Add /etc/ceph/ceph.conf sanity check 

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#330]
`ceph-salt status`/`ceph-salt apply` runs various sanity checks before applying the Salt Formula.

Ideally we would add a sanity check for every possible problem we can think of, because once the Salt Formula is running, it's difficult to return meaningful error messages to the user.

Here's an idea for a sanity check:

If `ceph-salt status`/`ceph-salt apply` detects a ceph cluster(s) running, it can find out the fsid(s) of that cluster (those clusters)
and then it can check `/etc/ceph/ceph.conf` - the fsid should match.

If no match, error.

**Comment by sebastian-philipp** [comment]
wouldn't it make more sense to have this in cephadm upstream?

**Comment by smithfarm** [comment]
> wouldn't it make more sense to have this in cephadm upstream?

Actually, I don't see any reason not to implement sanity checks in multiple places if they are relevant in multiple places.

As the description says: "once the Salt Formula is running, it's difficult to return meaningful error messages to the user" - so the idea is to catch environment problems *before* starting the Salt Formula, because Salt error reporting is sub-optimal.

**Comment by sebastian-philipp** [comment]
moved upstream: https://tracker.ceph.com/issues/48368
