### ISSUE TITLE
ceph-salt should not restart the Salt Master when running under SUMA

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#333]
(@ricardoasmarques thought of this issue during a brainstorming session - @smithfarm is just recording it)

ceph-salt is being designed to be compatible with SUMA.

If the Salt Master is SUMA, ceph-salt should not restart it.

At the moment, I (at least) am not aware of any way to programatically test whether the Salt Master is SUMA or not, but I'm pretty sure that such a mechanism exists.

**Comment by ricardoasmarques** [comment]
Since https://github.com/ceph/ceph-salt/pull/392 `ceph-salt` will no longer restart `salt-master` without user confirmation, so this issue is now fixed.
