### ISSUE TITLE
Retry zypper refresh

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#340]
Sometimes, `ceph-salt apply` fails during package installation due to a failure refreshing zypper repos, e.g:

```
Zypper command failure: Repository 'Clustering (SLE_15_SP2)' is invalid.
[network_cluster|https://download.opensuse.org/repositories/network:/cluster/SLE_15_SP2/] Valid metadata not found at specified URL
```

This is a known zypper issue that happens, for instance, during repo updates.

When this happens, the solution is to run `ceph-salt apply` again.

But to mitigate this problem, it would be great if `ceph-salt` can detect the error and retry zypper refresh again.

**Comment by smithfarm** [comment]
> it would be great if ceph-salt can detect the error and retry zypper refresh again

I don't see how `ceph-salt` could detect the error. Wouldn't the error-detection and retry logic have to be implemented in the `pkg.installed` Salt State?

**Comment by ricardoasmarques** [comment]
This is a duplicate of https://github.com/ceph/ceph-salt/issues/213
