### ISSUE TITLE
When steps and stages begin or end, write log message to the Salt minion log

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#342]
Execution modules can write messages to the minion logs. Quoting from https://docs.saltstack.com/en/latest/ref/modules/index.html#log-output

```
Log Output

You can call the logger from custom modules to write messages to the minion logs. The following code snippet demonstrates writing log messages:

import logging

log = logging.getLogger(__name__)

log.info("Here is Some Information")
log.warning("You Should Not Do That")
log.error("It Is Busted")
```

Stage/step begin/end is implemented using a macro.

It looks like the macros are implemented using modules.

So adding a `log.info("...")` to the relevant module should be feasible?

**Comment by smithfarm** [comment]
@ricardoasmarques In the minion logs, I see messages like this:

```
2020-08-25 17:45:26,921 [salt.state       :1902][INFO    ][14671] Executing state ceph_salt.begin_stage for [Dis
tribute SSH keys]
2020-08-25 17:45:26,924 [salt.state       :321 ][INFO    ][14671] {'desc': 'Distribute SSH keys'}
```

So I guess this is just a matter of ensuring that `/etc/salt/minion` has right setting for:

```
log_level: info
```

(if it is set to "warning" or "error", then the log will not show these "begin_stage", etc. messages)

**Comment by ricardoasmarques** [comment]
@smithfarm you are right

**Comment by ricardoasmarques** [comment]
But it would be great if we log events received on master, into `/var/log/ceph-salt.log` (similar to what is printed in `--non-interactive` mode)

**Comment by ricardoasmarques** [comment]
ATM, we only log those events if we receive them out of order, e.g. - https://github.com/ceph/ceph-salt/blob/master/ceph_salt/execute.py#L367

**Comment by smithfarm** [comment]
> But it would be great if we log events received on master, into `/var/log/ceph-salt.log`
> (similar to what is printed in `--non-interactive` mode)

Good idea! I opened https://github.com/ceph/ceph-salt/pull/344
