### ISSUE TITLE
Do not redirect 'bootstrap' output to a file

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#346]
With https://github.com/ceph/ceph/pull/36766 cephadm will log to a file which has the same name uised in ceph-salt [1].

We should consider removing this redirect from ceph-salt (if possible) or, at least, rename it.

[1] https://github.com/ceph/ceph-salt/blob/master/ceph-salt-formula/salt/ceph-salt/apply/cephbootstrap.sls#L84

**Comment by smithfarm** [comment]
As I wrote at https://github.com/ceph/ceph/pull/36766#issuecomment-680882277 `cephadm` still contains `print` statements that aren't logged. I don't think we should stop redirecting the output to a file as long as this is the case.

**Comment by ricardoasmarques** [comment]
https://github.com/ceph/ceph/pull/36766 has been merged
