### ISSUE TITLE
cephadm bootstrap --container-init

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#347]
https://github.com/ceph/ceph/pull/36822

We have to make sure:

* catatonit is installed
* it actually works
* call `cephadm boostrap --container-init` to enable this.

**Comment by smithfarm** [comment]
> catatonit is installed

. . . in the container image (I'm guessing)

**Comment by sebastian-philipp** [comment]
nonono on the host. that#s the point

**Comment by ricardoasmarques** [comment]
https://github.com/ceph/ceph/pull/36822 has been merged
