### ISSUE TITLE
"ceph-salt purge" should also purge ceph base container image from the cluster nodes

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#350]
When the Ceph cluster is bootstrapped (`ceph-salt apply`), the ceph base container image is pre-downloaded to all the nodes.

As a user, when I run `ceph-salt purge`, my expectation is that not only will the Ceph cluster go away, but also any artifacts that `ceph-salt` downloaded to the nodes will also be cleared.

**Comment by sebastian-philipp** [comment]
as we no longer download the image on all hosts in ceph-salt, I'd be :+1: to close this for now

**Comment by smithfarm** [comment]
OK, so the argument is "ceph-salt doesn't download the container image, therefore `ceph-salt purge` should not remove it", but does that really stand up? If I'm not mistaken, `ceph-salt purge` removes other things that are created by cephadm. So why not remove the container images as well?

I'd like to make `ceph-salt purge` as useful as possible for users. As a user, when I see the word "purge", the meaning I associate with it is "remove everything".

Does `cephadm` have `purge` functionality that removes everything, including the container images it downloaded? If it does, then perhaps it would make sense for `ceph-salt purge` to use it.

(I know from experience that users attempting to deploy clusters will want and need a way to restore their environment to a pristine state.)

**Comment by sebastian-philipp** [comment]
There is another reason to not delete images on `purge`: it slows down cluster deployment. I'd be really careful deleting images. IMO cephadm is the only component that can reasonably clean up images. 

Please reopen this, if you think this is still a good enhancement.
