### ISSUE TITLE
Orchestrated shutdown of the whole cluster

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#359]
The idea is to have a `ceph-salt shutdown` command to shutdown ceph cluster.

```
1) Find and admin node

2) Find the FSID

3) Execute `ceph osd ...` on that admin node:
# ceph osd set noout
# ceph osd set nobackfill
# ceph osd set norecover
# ceph osd set norebalance
# ceph osd set nodown
# ceph osd set pause
# ceph orch stop osd

4) Stop ceph service on all nodes:
# salt run \* 'systemctl stop ceph-<fsid>.target'
```

We may need a `ceph-salt startup` to start the cluster again.

See https://ceph.io/planet/how-to-do-a-ceph-cluster-maintenance-shutdown/ for more information.

**Comment by sebastian-philipp** [comment]
rethinking this: `ceph orch stop osd` might not work. The idea is to prevent any destructive calls in cephadm. and  `ceph orch stop osd` is exactly that: destructive.

Which means we'd need to build some bypass if we need to call this.

**Comment by smithfarm** [comment]
The blog post says to stop services in the following order:

1. gateways
2. osds
3. mons/mgrs

It seems reasonable to start them in the reverse order.

**Comment by smithfarm** [comment]
There's another aspect to this:

The process of taking a cluster down is often combined with powering down the hardware. As @sebastian-philipp 's comment implies, it's a sensitive operation. I wonder whether `ceph-salt` really needs to be in the business of shutting down clusters and bringing them up again?

**Comment by ricardoasmarques** [comment]
This is indeed a very sensitive operation, and `ceph-salt` don't know where gateways/osds/mons/... are deployed to stop services on the correct order.

I believe it's not clear ATM if this should be implemented in `ceph-salt` or `cephadm` itself.

Due to the above reasons plus the risk of supporting a feature like this, I'm closing this issue until really needed.

**Comment by ricardoasmarques** [comment]
I've now learned that part of the `shutdown` / `startup` process is implemented in Deepsea, so we will need a similar implementation for "feature parity":

- https://github.com/SUSE/DeepSea/tree/99f5e23248cef9299d983a2fa2da4699aaa16eff/srv/salt/ceph/shutdown
- https://github.com/SUSE/DeepSea/tree/99f5e23248cef9299d983a2fa2da4699aaa16eff/srv/salt/ceph/startup

**Comment by ricardoasmarques** [comment]
> ... `ceph-salt` don't know where gateways/osds/mons/... are deployed to stop services ...

Perhaps, `ceph-salt` can use `ceph orch service stop <service>` to stop all daemons of a service
