### ISSUE TITLE
Adding a new minion should set 'cephadm' role by default

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#366]
When a new minion is added, that minion should automatically receive the 'cephadm' role by default.

**Comment by smithfarm** [comment]
If every node is going to get the role, what is the purpose of having the role in the first place?

Is there a use case for removing the `cephadm` role from a minion?

**Comment by ricardoasmarques** [comment]
Scenarios where you want to "not set cephadm" role:
- if you want ceph-salt to configure a timeserver, but you don't want ceph daemons running on that server
- if you want a separate admin node (will only be possible after implementing https://github.com/ceph/ceph-salt/issues/252)

**Comment by ricardoasmarques** [comment]
An alternative solution would be to "invert" the `cephadm` role, by renaming it to `non-cephadm`, and only set that role to nodes where we don't want ceph daemons running.

**Comment by smithfarm** [comment]
maybe, instead of having a "cephadm" role, there could be a pillar config parameter called "NoCephadm" which would take a list of minions that are **not** to be managed by cephadm.

(I guess this is the same as the "non-cephadm" role you proposed - so :+1: from my side)

**Comment by ricardoasmarques** [comment]
I understand the benefit of assuming that by default, all minions will be added to  `cephadm`, and then having a role to exclude some minions (which is the exception).

But on the other hand, I feel hesitant to introduce a role that is a negation of something.

I believe it's more natural to read that `if minion has role X, then Y will be done`, instead of `if minion has role X, then Y will NOT be done`.

I also wonder if keeping `cephadm` in favor of `non-cephadm` will be better in the future if we want to support something else than `cephadm` (just thinking loud)?

I'll close this issue for now.
