### ISSUE TITLE
set global container_image ceph config

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#370]
If bootstrap is not specified (e.g. upgrade scenario), ceph-salt must set ceph container_image:

```
ceph config set global container_image <image>
```

**Comment by sebastian-philipp** [comment]
1. if you run `ceph orch upgrade start --image ...` this is already done at the end of the upgrade process. 
2. if you upgrade from before cephadm, ceph-salt is not really doing anything with the image, except forwarding it to cephadm.

**Comment by sebastian-philipp** [comment]
wontfix?

**Comment by ricardoasmarques** [comment]
Well, since we are now using the image only on the bootstrap minion, I wonder if we should move `/containers/image/ceph` to `/cephadm_bootstrap/image`, to make it clear that changing it after day 1 will have no effect.
