### ISSUE TITLE
Missing sanity check: user "cephadm" must exist on all minions that have cephadm role

### ISSUE THREAD

**Issue by smithfarm** [ceph/ceph-salt#372]
Although the act of installing the `cephadm` package can be expected to create the `cephadm` user, this does not give us 100% certitude that the `cephadm` user will exist on all nodes where we expect it to. Users might delete the `cephadm` user, for example.

**Comment by ricardoasmarques** [comment]
This can only happen on `ceph-salt status`, because on `ceph-salt apply`/`update`/`reboot` the `cephadm` user will be recreated.

Relates to https://github.com/ceph/ceph-salt/issues/379

**Comment by ricardoasmarques** [comment]
Note that ceph-salt **explicitly** creates the `cephadm` user [1], which means it will be recreated, if needed, everytime `cephadm apply` is executed.`

I don't see a reason to add this check, so I'm now closing the issue.

Feel free to reopen it if I'm missing something.

[1] https://github.com/ceph/ceph-salt/blob/master/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls#L9-L15
