### ISSUE TITLE
hostnames cannot be fqdn

### ISSUE THREAD

**Issue by swiftgist** [ceph/ceph-salt#417]
This isn't a feature request, but more for information and tracking.  Possibly the README should say that `hostnamectl fqdn` is not supported or add a validation.

Here's the behavior: I use vagrant for 14 VMs.  With other recent changes, I've had an issue where my hostnames were not resolving from dnsmasq and were assigned ip addresses as hostnames.  So, I used `hostnamectl fqdn` as part of the setup.  The first  failure is that `ceph-salt` calls cephadm which fails with `use --allow-fqdn-hostname` in the log file.

If you change the call in `cephbootstrap.sls`, then `ceph-salt apply` will complete; however, the installation will not have an admin keyring.  So the containers started and that's it.

I'm forcing short hostnames now which is working.

**Comment by smithfarm** [comment]
@swiftgist Were the code changes you made to get `ceph-salt apply` to complete similar to these:

https://github.com/ceph/ceph-salt/pull/419

or different?

With #419 `ceph-salt apply` completed successfully for me in a FQDN environment. But of course #419 is not mergeable in its current form - see #420 for an explanation.
