### ISSUE TITLE
'ceph-salt' should require the correct 'ceph-salt-formula' version

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#427]
We already have `Requires: ceph-salt-formula` on `ceph-salt.spec`, but ideally we should have:

```
Requires:       ceph-salt-formula = <ceph_salt_version>
```

**Comment by ricardoasmarques** [comment]
@smithfarm do you know if this is possible to implement?

**Comment by sebastian-philipp** [comment]
Yeah, with something similar to 

https://github.com/ceph/ceph/blob/cc16516fd851ee9b8175fee18435a9b8b507bf77/ceph.spec.in#L356
