### ISSUE TITLE
ceph-salt apply to bootstrap ceph cluster fails waiting for admin node

### ISSUE THREAD

**Issue by nistiwar** [ceph/ceph-salt#443]
While bootstrap the minimal cluster using-
ceph-salt apply

times out waiting for admin node by all the cluster nodes..Logs:

```
 9642 2020-12-04 10:50:09,108 [INFO] [ceph_salt.execute] STAGE [END] "Find an admin host" on minion ***** (success=True)
 9643 2020-12-04 10:50:09,108 [INFO] [ceph_salt.execute] Reporting failure: [****] find an admin host EV(end_stage, Configure cephadm)
 9644 2020-12-04 10:50:09,133 [INFO] [ceph_salt.execute] Response:
 9645 {
 9646   "****": {
 9647     "jid": "20201204095820971641",
 9648     "out": "highstate",
 9649     "ret": {
 9650       "ceph_orch_|-find an admin host_|-find an admin host_|-set_admin_host": {
 9651         **"__id__": "find an admin host",**
 9652         "__run_num__": 55,
 9653         "__sls__": "ceph-salt.apply.cephconfigure",
 9654         "changes": {},
 9655         **"comment": "Timeout value reached."**,
 9656         "duration": 3065624.686,
 9657         "name": "find an admin host",
 9658         "result": false,
 9659         "start_time": "09:59:03.472258"
```

I think it is calling ceph_orch.set_admin_host which is not an available function in module ceph_orch.

```
Ceph-Admin-2:/usr/share/salt-formulas/states/ceph-salt/apply # cat -n  cephconfigure.sls |more
     1  {% import 'macros.yml' as macros %}
     2
     3  {% if 'cephadm' in grains['ceph-salt']['roles'] or 'admin' in grains['ceph-salt']['roles'] %}
     4
     5  find an admin host:
     6    **ceph_orch.set_admin_host:**
     7      - failhard: True
     8
     9  {% endif %}
    10
```
```
Ceph-Admin-2:~ # salt * sys.list_functions ceph_orch
*****:
    **- ceph_orch.ceph_configured
    - ceph_orch.configured
    - ceph_orch.fsid
    - ceph_orch.host_ls**
```
```	
Ceph-Admin-2:~ # salt * sys.list_functions ceph_salt
****:
    - ceph_salt.begin_stage
    - ceph_salt.begin_step
    - ceph_salt.end_stage
    - ceph_salt.end_step
    - ceph_salt.get_remote_grain
    - ceph_salt.hostname
    - ceph_salt.is_safety_disengaged
    - ceph_salt.probe_dns
    - ceph_salt.probe_fqdn
    - ceph_salt.probe_ntp
    - ceph_salt.probe_time_sync
    - ceph_salt.ssh
    - ceph_salt.sudo_rsync
```

I am trying to build a production cluster and am stuck at bootstrapping using ceph-salt all nodes wait for admin node for around 30 minutes and then it times out. Not sure if I am heading in the right direction, any insights would be helpful..

**Comment by smithfarm** [comment]
@nistiwar Which OS is your Salt cluster running on?

**Comment by smithfarm** [comment]
```
Ceph-Admin-2:~ # salt * sys.list_functions ceph_orch
*****:
    **- ceph_orch.ceph_configured
    - ceph_orch.configured
    - ceph_orch.fsid
    - ceph_orch.host_ls**
```

Hm, though I have never used `sys.list_functions`, it would appear to work only on Salt Modules. In this case, it is showing you the functions in `ceph-salt-formula/salt/_modules/ceph_orch.py`. The function `set_admin_host` resides in a completely different file within the Salt Formula: `ceph-salt-formula/salt/_states/ceph_orch.py`.

**Comment by nistiwar** [comment]
Its SLES15SP2 + SES7

**Comment by sebastian-philipp** [comment]
https://github.com/SUSE/doc-ses/issues/814

**Comment by nistiwar** [comment]
I guess I understand now what is going wrong. So basically apart from ceph public and ceph cluster network, all our machines are also also connected to a operations and maintenance network which is also the default route to internet. When we deploy ceph, the bootstrap node's monitor port is listening somehow to only this O&M network and not on ceph public network. This causes the admin node to not be able to connect to Monitor over ceph public network. it only works if I keep admin + monitor colocated, but then results in a clusters worse nighmares, a network partition.
Any suggestions how I can make this work. My ceph public network is not internet facing and it needs an O&M network for that purpose. How can I make my first monitor listen on a specific network and not the default O&M network? NMAP shows:

# nmap X.X.X.X (OnM Network)
Starting Nmap 7.91 ( https://nmap.org ) at 2020-12-07 08:29 GMT
Nmap scan report for X.X.X.X
Host is up (0.00010s latency).
Not shown: 979 filtered ports
PORT     STATE  SERVICE
22/tcp   open   ssh
3300/tcp closed ceph
6789/tcp closed ibm-db2-admin
6839/tcp closed unknown
6881/tcp closed bittorrent-tracker
6901/tcp closed jetstream
6969/tcp closed acmsoda
7000/tcp closed afs3-fileserver
7001/tcp closed afs3-callback
7002/tcp closed afs3-prserver
7004/tcp closed afs3-kaserver
7007/tcp closed afs3-bos
7019/tcp closed doceri-ctl
7025/tcp closed vmsvc-2
7070/tcp closed realserver
7100/tcp closed font-service
7103/tcp closed unknown
7106/tcp closed unknown
7200/tcp closed fodms
7201/tcp closed dlip

# nmap Y.Y.Y.Y (Ceph Public network)
Starting Nmap 7.91 ( https://nmap.org ) at 2020-12-07 08:26 GMT
Nmap scan report for Y.Y.Y.Y
Host is up (0.000069s latency).
Not shown: 999 filtered ports
PORT   STATE SERVICE
22/tcp open  ssh

But surprisingly on the bootstrap node, its is listening to ceph public IP:
# ss -lnp | grep 6789
tcp                LISTEN              0                    128                                                                                      Y.Y.Y.Y:6789                                             0.0.0.0:*                       users:(("ceph-mon",pid=368158,fd=37))

I am clueless why the port is listening on Y.Y.Y.Y network and the client is still not able to connect and nmap shows only ssh listening to it and 6789 listening on X.X.X.X network

**Comment by smithfarm** [comment]
You had to set an IP address in `/cephadm_bootstrap/mon_ip`? This determines which network the first MON will listen on.

```
ceph-salt config ls /cephadm_bootstrap/mon_ip
```

**Comment by nistiwar** [comment]
I am deploying ses7, mon ip is auto populated after #ceph-salt update --reboot before applying..
and it is populating it correctly..On the node as well, I see the process is listening on public network :
# ss -lnp | grep 6789
tcp                LISTEN              0                    128                                                                                      X.X.X.X(Public Network):6789                                             0.0.0.0:*                       users:(("ceph-mon",pid=368158,fd=37))
 
But when I run a nmap from another node, it is not detecting port 6789 on X.X.X.X network but is seen on Y.Y.Y.Y network. Trying to connect to via telnet X.X.X.X 6789 gives me a no route to Host. A syn packet is send to the monitor node, but is never acknowledged.

**Comment by smithfarm** [comment]
That sounds weird. When deploying SES7 I always set `/cephadm_bootstrap/mon_ip` explicitly and verify it in `ceph-salt config ls` before running `ceph-salt apply`.

Can you confirm that firewall is OFF on all nodes?

Can you confirm again that `ceph-salt config ls /cephadm_bootstrap/mon_ip` (run on the Salt Master node) shows the correct address?

Can you confirm that `ceph config get mon public_network` (run on the bootstrap node) shows the correct address?

**Comment by nistiwar** [comment]
You were right, it was our favorite firewall which got started after a reboot on the bootstrap node after a reboot which was messing around. My bad completely, apologies for all the confusion. No sure how should I trash this bug, closing with comments will do or..?

Thanks for all your help..I  was over confident about the firewall as I checked it to be not running initially..skipped disabling it as well.

**Comment by nistiwar** [comment]
Just one comment though, I still didnt find the need to set  /cephadm_bootstrap/mon_ip. In SES7, it requires to set a bootstrap node, and then update the nodes using ceph-salt update --reboot. This auto-populates the mon_ip based on the bootstrap node before ceph-salt apply.

**Comment by smithfarm** [comment]
How does the "auto-population" know the correct IP address when the node has multiple IP addresses?

**Comment by nistiwar** [comment]
Salt is identifying minions by a FQDN, which resolves to a particular IP from DNS. When a minion is added a role of bootstrap by name, the IP that reflects in DNS is used..apologies for delay. Got tied up in an urgent delivery.

**Comment by smithfarm** [comment]
Without the ability to set `/cephadm_bootstrap/mon_ip`, the public network would be dictated by DNS. 

Imagine a bootstrap node with IP addresses in three different networks. The minion name can only point to one of those, and ceph-salt/cephadm has no way of knowing whether that one is in the intended public network. Imagine the intended public network really is different? For that that case, we have the `/cephadm_bootstrap/mon_ip` config parameter, which causes ceph-salt to specify the correct MON IP in the `cephadm bootstrap` invocation.
