### ISSUE TITLE
Does this project support opensuse leap 15.2 ?

### ISSUE THREAD

**Issue by muryliang** [ceph/ceph-salt#448]
I try to install SES 7  on opensuse leap 15.2, and follow the deploy guide on https://documentation.suse.com/ses/7/html/ses-all/deploy-cephadm.html. 

I use ceph-salt-15.2.14+1603183994.g323e812-lp152, and  ceph-15.2.8.80+g1f4b6229ca-lp152.2.9.1. And the registry is set to docker.io/ceph/ceph:v15.2, just as the Readme.md of this project say.(But I find that the container images are centos 8 instead of opensuse) 

Everything is fine until  "ceph-salt apply".   It always report error during step  "Add host to ceph orchestrator", and the error msg is:(c2 is the bootstrap node configured in ceph-salt config) 

[2021-02-02 07:55:52.438744] [c3              ] Finished successfully                                                                       [1/6069]
[2021-02-02 07:55:52.444935] [c4              ] Finished successfully                                                                               
[2021-02-02 07:55:52.448664] [c1              ] Finished successfully
[2021-02-02 07:55:53.949629] [c2              ] [STAGE] [END  ] Wait until ceph orch is available
[2021-02-02 07:55:53.953269] [c2              ] [STAGE] [BEGIN] Add host to ceph orchestrator
[2021-02-02 07:55:56.721798] [c2              ] Finished with failures

Failure in minion: c2
__id__: add host to ceph orch
__run_num__: 83
__sls__: ceph-salt.apply.cephorch
changes: {}
comment: "Warning: Permanently added 'c2,172.20.0.22' (ECDSA) to the list of known\
  \ hosts.\r\nError EINVAL: New host c2 (c2) failed check: ['usage:  [-h] [--image\
  \ IMAGE] [--docker] [--data-dir DATA_DIR]', '        [--log-dir LOG_DIR] [--logrotate-dir\
  \ LOGROTATE_DIR]', '        [--unit-dir UNIT_DIR] [--verbose] [--timeout TIMEOUT]\
  \ [--retry RETRY]', '        [--env ENV]', '        {version,pull,inspect-image,ls,list-networks,adopt,rm-daemon,rm-cluster,run,shell,enter,ceph-v
olume,unit,logs,bootstrap,deploy,check-host,prepare-host,add-repo,rm-repo,install,registry-login,gather-facts}',\
  \ '        ...', ': error: unrecognized arguments: --container-init']"
duration: 768.166
name: add host to ceph orch
result: false
start_time: '15:55:53.947307'
state: ceph_orch_|-add host to ceph orch_|-add host to ceph orch_|-add_host

Finished execution of ceph-salt formula

Summary: Total=4 Succeeded=3 Warnings=0 Failed=1

And I try the "ceph orch host add c2" command manually, which still report the above "unrecognized arguments: --container-init"   error.

**Comment by smithfarm** [comment]
"support" is not the right word, but it _should_ work provided you have the following repo on all the cluster nodes (including the admin node): https://download.opensuse.org/repositories/filesystems:/ceph:/octopus/openSUSE_Leap_15.2/

**Comment by muryliang** [comment]
I already installed the repo on every node.  All my nodes are qemu virtual machines, I have tried many times, but  "ceph orch host add" will always fail with the above error.   

Then I tried ceph official document's cephadm deploy method(use official's cephadm script), which has no problem, the "ceph orch host add" can be executed. So I guess there might be something not compatible among Leap 15.2's ceph version(15.2.8.80+g1f4b6229ca-lp152.2.9.1)  and  ceph-salt(15.2.14)  and  cephadm(15.2.8.80+g1f4b6229ca-lp152.2.9.1)

**Comment by sebastian-philipp** [comment]
the error is:
```
"Warning: Permanently added 'c2,172.20.0.22' (ECDSA) to the list of known  \ hosts.
Error EINVAL: New host c2 (c2) failed check: ['usage:  [-h] [--image  \ IMAGE] [--docker] [--data-dir DATA_DIR]
        [--log-dir LOG_DIR] [--logrotate-dir  \ LOGROTATE_DIR]
        [--unit-dir UNIT_DIR] [--verbose] [--timeout TIMEOUT]  \ [--retry RETRY]
        [--env ENV]
        {version,pull,inspect-image,ls,list-networks,adopt,rm-daemon,rm-cluster,run,shell,enter,ceph-v
olume,unit,logs,bootstrap,deploy,check-host,prepare-host,add-repo,rm-repo,install,registry-login,gather-facts}
: error: unrecognized arguments: --container-init']"
```

**Comment by sebastian-philipp** [comment]
right. https://github.com/SUSE/ceph/commit/745a9fee43677a3799721fbe070d1963de7babb9 never went upstream.

**Comment by muryliang** [comment]
Thanks for your help,  I have found the exact command  produced this error: `ssh c2 cephadm  check-host --container-init --expect-hostname c2`, the `--container-init`  flag  is introduced in at v15.2.8.  I may try to deploy with v15.2.7 container image instead.  

~~I also want to know if there exists opensuse Octopus version container image,  as the `docker.io/ceph/ceph` only have centos based image, and after searching OBS, I can only find ceph v16.0 image.~~
Ok, I have found image repo,  `https://download.opensuse.org/repositories/filesystems:/ceph:/octopus/images/`

**Comment by smithfarm** [comment]
> I also want to know if there exists opensuse Octopus version container image

~Yes: registry.opensuse.org/filesystems/ceph/octopus/upstream/images/ceph/ceph~

Sorry - it's this one: `registry.opensuse.org/filesystems/ceph/octopus/images/ceph/ceph`

**Comment by muryliang** [comment]
> > I also want to know if there exists opensuse Octopus version container image
> 
> ~Yes: registry.opensuse.org/filesystems/ceph/octopus/upstream/images/ceph/ceph~
> 
> Sorry - it's this one: `registry.opensuse.org/filesystems/ceph/octopus/images/ceph/ceph`

Thanks,  the `podman pull` operation from registry.opensuse.org is very slow here.  And the 15.2.7 version has failed with another `unrecognized config option 'mgr/cephadm/container_init'`  error,  I will pull the suse image down and push on to the docker.io, and try again.

**Comment by smithfarm** [comment]
@muryliang The upstream (docker.io) images have not been tested with ceph-salt and I would not expect them to work. Please use the image from `registry.opensuse.org/filesystems/ceph/octopus/images/ceph/ceph` only.

**Comment by muryliang** [comment]
> @muryliang The upstream (docker.io) images have not been tested with ceph-salt and I would not expect them to work. Please use the image from `registry.opensuse.org/filesystems/ceph/octopus/images/ceph/ceph` only.

I tried the  `registry.opensuse.org/filesystems/ceph/octopus/images/ceph/ceph` image, it works, now everything is fine.  I suggest modify the `README.md` file  because it use `/cephadm_bootstrap/ceph_image_path set docker.io/ceph/ceph:v15.2.2` as the example.

**Comment by smithfarm** [comment]
@muryliang Thanks: #450

**Comment by sebastian-philipp** [comment]
This is a real bug: https://tracker.ceph.com/issues/49223 See the workaround.

**Comment by tserong** [comment]
Closing again (upstream issue is long since fixed)
