### ISSUE TITLE
cephadm user/group created by ceph-salt inconsistent with user created by cephadm package

### ISSUE THREAD

**Issue by tserong** [ceph/ceph-salt#460]
If you installed the RPM package of `cephadm`, it will create a cephadm user and group automatically if such don't already exist:

https://github.com/ceph/ceph/blob/d4fc4ecf0aac78f1c767e7a77599364bdf29e062/ceph.spec.in#L1548-L1551

```sh
getent group cephadm >/dev/null || groupadd -r cephadm
getent passwd cephadm >/dev/null || useradd -r -g cephadm -s /bin/bash -c "cephadm user for mgr/cephadm" -d %{_sharedstatedir}/cephadm cephadm
```

Note that the user and group are both marked system (`-r`), the default gid of the cephadm user is the cephadm group, and the home directory is /var/lib/cephadm.

Compare with ceph-salt:

https://github.com/ceph/ceph-salt/blob/e646be770c40c348c2a10ffaa23149a0ad81811a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls#L5-L15

This:
* creates the "users" group (which almost certainly already exists)
* puts the cephadm user in that group
* neither user nor group are marked system
* the home directory is /home/cephadm

Ideally, we would change ceph-salt to match the cephadm package, as follows:

```diff --git a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
index a796fcc..090c67d 100644
--- a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
+++ b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
@@ -4,14 +4,15 @@
 
 create ssh user group:
   group.present:
-    - name: users
+    - name: cephadm
+    - system: True
 
 create ssh user:
   user.present:
     - name: cephadm
-    - home: /home/cephadm
-    - groups:
-      - users
+    - gid: cephadm
+    - system: True
+    - home: /var/lib/cephadm
     - failhard: True
 
 install sudo:
@@ -36,7 +37,7 @@ create ssh dir:
   file.directory:
     - name: /home/cephadm/.ssh
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0700'
     - makedirs: True
     - failhard: True
@@ -46,7 +47,7 @@ create ceph-salt-ssh-id_rsa:
   file.managed:
     - name: /home/cephadm/.ssh/id_rsa
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0600'
     - contents_pillar: ceph-salt:ssh:private_key
     - failhard: True
@@ -56,7 +57,7 @@ create ceph-salt-ssh-id_rsa.pub:
   file.managed:
     - name: /home/cephadm/.ssh/id_rsa.pub
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0644'
     - contents_pillar: ceph-salt:ssh:public_key
     - failhard: True
```

Unfortunately, we can't do that, because it won't work for existing deployments, which already have a cephadm user. We can't change the home directory (because that would require moving files), and we can't change the default gid (because that would require changing file ownership in the home directory). Well, we could implement salt states to _try_ to do those things, but alas, on a running system, the home directory is in use, so this is all just going to be horrible.

I think the closest we can get to ideal is this:

```diff --git a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
index a796fcc..eac37dc 100644
--- a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
+++ b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
@@ -4,14 +4,16 @@
 
 create ssh user group:
   group.present:
-    - name: users
+    - name: cephadm
+    - system: True
 
 create ssh user:
   user.present:
     - name: cephadm
+    - system: True
     - home: /home/cephadm
     - groups:
-      - users
+      - cephadm
     - failhard: True
 
 install sudo:
@@ -36,7 +38,7 @@ create ssh dir:
   file.directory:
     - name: /home/cephadm/.ssh
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0700'
     - makedirs: True
     - failhard: True
@@ -46,7 +48,7 @@ create ceph-salt-ssh-id_rsa:
   file.managed:
     - name: /home/cephadm/.ssh/id_rsa
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0600'
     - contents_pillar: ceph-salt:ssh:private_key
     - failhard: True
@@ -56,7 +58,7 @@ create ceph-salt-ssh-id_rsa.pub:
   file.managed:
     - name: /home/cephadm/.ssh/id_rsa.pub
     - user: cephadm
-    - group: users
+    - group: cephadm
     - mode: '0644'
     - contents_pillar: ceph-salt:ssh:public_key
     - failhard: True
```

That'll give a cephadm user which actually is still in the default "users" group (because that's what the underlying `useradd` command will do), but is _also_ in the cephadm group. And, at least the cephadm group is created correctly.

Why am I proposing this change? Because in locked-down environments, where `/etc/ssh/sshd_config` specifies a limited set of groups in `AllowGroups`, we need the cephadm user to be in the cephadm group, so _that_ group can be added to AllowGroups, rather than adding "users" and opening things up too much.

**Comment by sebastian-philipp** [comment]
could you remove the ability of ceph-salt to create the user in the first place? Maybe only for new deployments?

**Comment by tserong** [comment]
> could you remove the ability of ceph-salt to create the user in the first place? Maybe only for new deployments?

Oooh, that's a good thought. Then we just rely on the cephadm package to make sure the user is present. I'll see if I can make that work in a way that doesn't mess with existing deployments.

**Comment by tserong** [comment]
So, I thought this would perhaps be a good approach:

```diff --git a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
index a796fcc..e34b81a 100644
--- a/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
+++ b/ceph-salt-formula/salt/ceph-salt/common/sshkey.sls
@@ -2,18 +2,6 @@
 
 {{ macros.begin_stage('Ensure SSH keys are configured') }}
 
-create ssh user group:
-  group.present:
-    - name: users
-
-create ssh user:
-  user.present:
-    - name: cephadm
-    - home: /home/cephadm
-    - groups:
-      - users
-    - failhard: True
-
 install sudo:
   pkg.installed:
     - pkgs:
@@ -34,9 +22,9 @@ configure sudoers:
 # make sure .ssh is present with the right permissions
 create ssh dir:
   file.directory:
-    - name: /home/cephadm/.ssh
+    - name: {{ salt['user.info']('cephadm').home }}/.ssh
     - user: cephadm
-    - group: users
+    - group: {{ salt['user.info']('cephadm').gid }}
     - mode: '0700'
     - makedirs: True
     - failhard: True
```

...and similar changes to other stanzas in that file and elsewhere that need to fill out the cephadm user's group, home directory, etc.

If that worked, it would all just "do the right thing" for both existing installs, which already have a cephadm user, and for new deployments, because when the cephadm package is installed, it'll create the cephadm user and group, and everything should be there.

Turns out this approach does seem to be viable for existing installs, but for new deployments, we have a chicken-and-egg problem with the installation of the cephadm package. Because of the way salt works, at the time the jinja is compiled, the cephadm package isn't installed yet (the relevant pkg.installed stanza from ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls doesn't apply until _after_ the templates are all complied), so the calls to `{{ salt['user.info']('cephadm').home }}` raise a "Data failed to compile: ... Jinja variable 'dict object' has no attribute 'home'" error, because that user doesn't exist yet.

Now, because I am evil, I have a potential workaround, but it's ugly as hell. Check this out:

```diff --git a/ceph-salt-formula/salt/ceph-salt/apply/init.sls b/ceph-salt-formula/salt/ceph-salt/apply/init.sls
index 745322d..0a7677c 100644
--- a/ceph-salt-formula/salt/ceph-salt/apply/init.sls
+++ b/ceph-salt-formula/salt/ceph-salt/apply/init.sls
@@ -1,5 +1,7 @@
 {% if grains['id'] in pillar['ceph-salt']['minions']['all'] %}
 
+# {{ salt['pkg.install']('cephadm') }}
+
 include:
     - ..reset
     - ..common.sshkey
```

That forces salt to run `pkg.install cephadm` in the jinja compile phase, so it should be there by the time we need it later to call `salt['user.info']('cephadm').home`. If the install fails, you will see an error dumped to the console, something like:

```
node1:
    Data failed to compile:
----------
    Rendering SLS '...' failed: Problem running salt function in Jinja template: Zypper command failure: Running scope as unit: run-rbe3643dcd14141c393f575343f945b5d.scope
Package 'cephadm' not found.; line 1
```

If it succeeds, everything should just run through fine. At least, it does in the small test I knocked up; I haven't applied this hack to the whole of ceph-salt itself yet.

What do you think? Is that bit of evil worth pursuing? ;-)

**Comment by smithfarm** [comment]
@tserong I think it's worth pursuing, and thanks for your detailed write-up.

Another thought that occurred to me is: patch cephadm so it always:

1. checks if there is an existing `cephadm` user
2. if there is, adds it to the `cephadm` group.

The thing about ceph-salt is: it's only supposed to be used for Day 1 ops (everything up to and including `cephadm bootstrap`). So, in an existing cluster, you won't get a chance to fix the problem using ceph-salt.

**Comment by smithfarm** [comment]
Is the following correct?

1. In the case when the cephadm user does not exist, cephadm creates it *and* does foo, bar and blatz to it.
2. In the case when the cephadm user *does* exist, cephadm doesn't touch it.

If it *is* correct, I would argue that is a bug in cephadm. In the latter case, cephadm should also check and make sure that "foo, bar, and blatz" have been applied to the cephadm user - not just leave it as it is.

**Comment by tserong** [comment]
> The thing about ceph-salt is: it's only supposed to be used for Day 1 ops (everything up to and including `cephadm bootstrap`). So, in an existing cluster, you won't get a chance to fix the problem using ceph-salt.

You can still re-run `ceph-salt apply` and it'll reapply a bunch of state (but obviously won't re-run the bootstrap). So, if we were to take my initial (non-ideal) proposed fix to ceph-salt, then any existing deployments that re-ran `ceph-salt apply` with that fix, would see a change to the cephadm group.



> Is the following correct?
> 
> 1. In the case when the cephadm user does not exist, cephadm creates it _and_ does foo, bar and blatz to it.
> 2. In the case when the cephadm user _does_ exist, cephadm doesn't touch it.

Yep, that's correct. Per https://github.com/ceph/ceph/blob/d4fc4ecf0aac78f1c767e7a77599364bdf29e062/ceph.spec.in#L1548-L1551, if there's no cephadm group, it gets created, and if there's no cephadm user, that gets created with its gid set to cephadm, shell /bin/bash and home set to /var/lib/cephadm. If either group or user already exists, they are not touched.

**Comment by smithfarm** [comment]
> Yep, that's correct. Per https://github.com/ceph/ceph/blob/d4fc4ecf0aac78f1c767e7a77599364bdf29e062/ceph.spec.in#L1548-L1551, if there's no cephadm group, it gets created, and if there's no cephadm user, that gets created with its gid set to cephadm, shell /bin/bash and home set to /var/lib/cephadm. If either group or user already exists, they are not touched.

So, to re-phrase my question: wouldn't it make more sense if cephadm made sure any existing `cephadm` user has:

1. its gid set to cephadm,
2. its shell set to /bin/bash, and
3. its home set to /var/lib/cephadm

?

Then nobody would have to worry about what ceph-salt is doing.

**Comment by smithfarm** [comment]
Regarding the idea of running `pkg.install cephadm` in the Jinja rendering phase... will that cause cephadm to be installed on all the Salt "minions", or just on the Salt "master"?

**Comment by sebastian-philipp** [comment]
we need cephadm everywhere. for debugging purpose.

**Comment by tserong** [comment]
The way I wrote it above, it'll end up on all salt minions vs. the current implementation which targets all minions with the cephadm role. If we want to limit it at all, we only want to limit it to the latter, because like Sebastian said, we generally want it installed everywhere.

**Comment by smithfarm** [comment]
As part of this change, then, should we rip out the `cephadm` role and document that all minions get it?

**Comment by smithfarm** [comment]
> like Sebastian said, we generally want it installed everywhere

Well, for some definition of "everywhere", yes. But that would not extend to clients. Wasn't there a use-case for having ceph-salt manage client machines as well as machines that are part of the Ceph cluster itself? 

My memory is foggy, but it seems like we should be careful if we are to render the entire cephadm role useless.

**Comment by tserong** [comment]
> So, to re-phrase my question: wouldn't it make more sense if cephadm made sure any existing `cephadm` user has:
> 
>     1. its gid set to cephadm,
> 
>     2. its shell set to /bin/bash, and
> 
>     3. its home set to /var/lib/cephadm
> 
> 
> ?

Probably, yes. But, that might get annoying to implement if it requires changing file ownership or moving directories around. Still, that's a separate piece of work to this issue.

> As part of this change, then, should we rip out the `cephadm` role and document that all minions get it?

I'd rather not - I'd like to just fix the way ceph-salt uses the cephadm user and group, and not mess with the semantics of anything else.

> My memory is foggy, but it seems like we should be careful if we are to render the entire cephadm role useless.

Agreed. I'll try to arrange my evil appropriately.
