### ISSUE TITLE
ceph-bootstrap config displaying Dashboard password

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#48]
ceph-bootstrap config displaying Dashboard password:

```
# ceph-bootstrap config /Deployment/Dashboard/password set admin
# ceph-bootstrap config /Deployment/Dashboard ls
o- Dashboard ........................................ [...]
  o- password ..................................... [admin]
  o- username ..................................... [admin]
```

**Comment by sebastian-philipp** [comment]
Can't we simply remove the dashboard's password from ceph-bootstrap and just print the generated password? IMO users should create a proper password on first login anyway.

Relates to https://tracker.ceph.com/issues/43694

**Comment by ricardoasmarques** [comment]
> Can't we simply remove the dashboard's password from ceph-bootstrap and just print the generated password? IMO users should create a proper password on first login anyway.
> 
> Relates to https://tracker.ceph.com/issues/43694

That would break `sesdev`: https://github.com/SUSE/sesdev/blob/master/seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2#L98

**Comment by sebastian-philipp** [comment]
Hm. In any case, cephadm should make sure users update their PW on first login.

**Comment by smithfarm** [comment]
Forcing the user to change the password is a PITA for integration testing. Just saying... I would think that dashboard developers themselves would want to have a way to set the dashboard admin password and not have cephadm forcing them to change it in order to log in.

(In other words, IMHO if a "forced password change on first login" feature is added, there should be a way to disable it.)

**Comment by sebastian-philipp** [comment]
> Forcing the user to change the password is a PITA for integration testing. Just saying... I would think that dashboard developers themselves would want to have a way to set the dashboard admin password and not have cephadm forcing them to change it in order to log in.
> 
> (In other words, IMHO if a "forced password change on first login" feature is added, there should be a way to disable it.)

would it be enough to just return the generated password then? that's what is done by vstart for example.
