### ISSUE TITLE
ceph-salt not found

### ISSUE THREAD

**Issue by oldManLemon** [ceph/ceph-salt#483]
Which repo is ceph-salt suppose to be found in when running zypper in ceph-salt as I am unable to get this working which is like step 1 of installing ceph cluster on Suse Enterprise 15.3 SP3. 

I am following these instructions. https://documentation.suse.com/ses/7/html/ses-all/deploy-bootstrap.html

I assume I'm missing a repo or something obvious like I am supposed to pull it from here or set the repo to github or something?

Kind Regards

```
Loading repository data...
Reading installed packages...
Package 'ceph-salt' not found.
Resolving package dependencies...
Nothing to do.
```

**Comment by tserong** [comment]
Official SUSE builds of ceph-salt for SLE are only available as part of the SUSE Enterprise Storage product, which is no longer available to new customers (see https://www.suse.com/download/ses/). If you're an existing customer, you should have access to the appropriate repositories as part of your subscription.  For Ceph on openSUSE, please see https://en.opensuse.org/openSUSE:Ceph
