### ISSUE TITLE
Always pull image before service deployment

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#52]
Make use of `cephadm pull` command to pull images before executing `cephadm bootstrap`.

**Comment by rjfd** [comment]
We already doing that here: https://github.com/SUSE/ceph-bootstrap/blob/master/ceph-salt-formula/salt/ceph-salt/cephbootstrap.sls#L20

Or are you talking about another thing?

**Comment by ricardoasmarques** [comment]
ATM we are only pulling it if `pillar['ceph-salt']['container']['images']['ceph']` is defined. We should always pull it.

**Comment by rjfd** [comment]
The problem is that we need to know which image to pull, and that is defined in that pillar entry

**Comment by rjfd** [comment]
which image is pulled by default by `cephadm pull`?

**Comment by ricardoasmarques** [comment]
Per our discussion, we should not pull the default image, so I'm closing this issue in favor of https://github.com/SUSE/ceph-bootstrap/issues/53

**Comment by sebastian-philipp** [comment]
> which image is pulled by default by `cephadm pull`?

That's a default value within cephadm itself. It might actually make sense to make this default configurable  in order to prevent users from downloading the centos image when directly calling cephadm commands.
