### ISSUE TITLE
Deployment must be idempotent

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#58]
ATM, OSD deployment fails when `ceph-bootstrap deploy` is executed a second time:

![Screenshot from 2020-01-31 11-36-54](https://user-images.githubusercontent.com/14297426/73536561-13cb0000-441e-11ea-8ef8-3bc493f4fcff.png)

**Comment by sebastian-philipp** [comment]
looking at the screenshot, this looks like a cephadm bug to me. Not something we should fix here.

**Comment by ricardoasmarques** [comment]
Hmm... let's wait until https://github.com/ceph/ceph/pull/32972 is merged and then test it again

**Comment by bk201** [comment]
This should work on current master + cephadm, re-deploy no longer fails on OSD create.

**Comment by ricardoasmarques** [comment]
ATM, `ceph-salt` does now allow to re-run `deploy` on all host:
```
master:~ # ceph-salt deploy
Checking if ceph-salt formula is available...
Syncing minions with the master...
Checking if there is an existing deployment...
Cluster is already deployed, please apply the deployment to a single minion at a time: "ceph-salt deploy <minion_id>"
```

Support for re-run `deploy` on all hosts is tracked on https://github.com/ceph/ceph-salt/issues/173
