### ISSUE TITLE
cephadm's default image

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph-salt#59]
In case someone manually starts `cephadm` on a minion for debugging purposes, there is a chance that a user will not specify an image. 

If we could specify the default image for cephadm in a config file, we no longer need to worry about users accidentally pulling the default image.

Changing the default image doesn't have an impact on the image used by calls from the ceph-mgr, as the mgr always specifies the image when calling cephadm.

Thoughts? 

See also #53 and #52

**Comment by ricardoasmarques** [comment]
I like the idea, it makes sense to me, but this discussion should be moved to "cephadm" since it's not a "ceph-bootstrap" discussion.

As soon as "cephadm" supports configuring the default image, we should then adapt "ceph-bootstrap" accordingly.

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/43937

**Comment by ricardoasmarques** [comment]
From the `ceph-bootstrap` POV, we can solve this by setting the `CEPHADM_IMAGE` environment variable in all minions.

**Comment by sebastian-philipp** [comment]
That would certainly make my life easier. Is this ok for you?

**Comment by ricardoasmarques** [comment]
The following upstream ticket could fix the issue in a more reliable way: https://tracker.ceph.com/issues/44440

**Comment by ricardoasmarques** [comment]
cc @smithfarm

**Comment by smithfarm** [comment]
Having ceph-salt set the image via an environment variable on all minions sounds weak and prone to failure.

When setting the environment variable, how does ceph-salt guarantee that the environment variable will always be set correctly when the cluster administrator logs in? Is there a way to set environment variables globally for the whole system via YaST?

A site might use ceph-salt for provisioning only, and run `cephadm bootstrap` manually. How does the environment variable get set in that case?

What if the user adds a node later on?

**Comment by ricardoasmarques** [comment]
As soon as https://tracker.ceph.com/issues/43937 is implemented, it will be possible to set the default Ceph container image path via a MON config-key.

`ceph-salt` should then be adapted to set that MON config-key.

**Comment by ricardoasmarques** [comment]
The approach we are currently working on is:

- ceph-salt must explicitly pull the image 
- ceph images must have a "ceph=True" Label [1]
- by default, cephadm will use the latest local ceph image [2]

[1] https://github.com/ceph/ceph-container/pull/1604
[2] https://github.com/ceph/ceph/pull/33829

**Comment by ricardoasmarques** [comment]
Fixed by https://tracker.ceph.com/issues/44440
