### ISSUE TITLE
Allow explicit set Mon IP

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#64]
ATM, ceph-bootstrap always uses the IP address from the `fqdn_ip4` grain to configure Monitors.

This address can be used by default, but it should be possible to explicitly change it to a different value.

This can be done in the `/Deployment` group, e.g.:
```
 ...
 o- Deployment ............................................................... [...]
  | ...
  | o- Mon ............................................................... [enabled]
  | | o- node1.ceph.com .......................................... [192.169.100.201]
 ...
```

When implementing this we should remove the `CephNodeFqdnResolvesToLoopback` validation when adding a `minion`, and only validate IPs before the deployment.

**Comment by sebastian-philipp** [comment]
hm. we probably need to add support for adding ips in cephadm itself?

I think that we're not the only ones who want to add raw IPs. having working DNS might be too much for everyone

**Comment by ricardoasmarques** [comment]
@sebastian-philipp This is about the IP address used on the following commands:
- `cephadm bootstrap --mon-ip ...`
- `ceph orchestrator mon update ...`

Since those commands are already receiving the ip address, I think there's nothing to do in `cephadm`.
