### ISSUE TITLE
Improve states and steps descriptions

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#70]
For instance, some stages start with `Install ...` others with `Setting up ...`.

![Screenshot from 2020-02-07 17-54-09](https://user-images.githubusercontent.com/14297426/74053005-e0b2de80-49d2-11ea-9deb-6603131b6de0.png)

We should find a more consistent description for "states" and "steps".

**Comment by smithfarm** [comment]
This is something that can, and probably should, wait until ceph-salt development has progressed further and most of the features are in.

Or it can be done in stages.

**Comment by ricardoasmarques** [comment]
We may also need to add or remove `stages` / `steps`, change `stages` to `steps` or vice-versa.

**Comment by ricardoasmarques** [comment]
At some point, it would be great to review/improve `ceph-salt config` help texts too - https://github.com/ceph/ceph-salt/blob/master/ceph_salt/config_shell.py#L253
