### ISSUE TITLE
Admin role

### ISSUE THREAD

**Issue by ricardoasmarques** [ceph/ceph-salt#71]
ATM, `ceph-common` and `/etc/ceph/ceph.client.admin.keyring` are installed on all "mons".

Instead, we should have a dedicated "Admin" role, and only install ceph tools on minions that have that role.

Links
https://github.com/ceph/ceph/pull/33793

**Comment by smithfarm** [comment]
Please be sure to update https://confluence.suse.com/display/SUSEEnterpriseStorage/How+to+use when this feature is implemented.

**Comment by ricardoasmarques** [comment]
The scope of this issue is about to change.

@sebastian-philipp can you please comment on what we are planning to change here?

**Comment by ricardoasmarques** [comment]
Per our discussion, `ceph-salt` should not install `ceph-common` on "Admin" nodes. This will be tracked on a separate issue: https://github.com/ceph/ceph-salt/issues/120

**Comment by smithfarm** [comment]
@ricardoasmarques Will `ceph-common` be installed on any nodes at all?

**Comment by ricardoasmarques** [comment]
@smithfarm https://github.com/ceph/ceph-salt/issues/120 will not install `ceph-common` at all

**Comment by ricardoasmarques** [comment]
> Please be sure to update https://confluence.suse.com/display/SUSEEnterpriseStorage/How+to+use when this feature is implemented.

Done
